package com.autonavi.directl.bean;

import java.util.Date;

/**
 * AbstractTSpeedCase generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTSpeedCase implements java.io.Serializable {

	// Fields

	private Long id;

	private Float maxSpeed;

	private Long cxTime;

	private String deviceId;

	private Date crtdate;

	private String crtman;

	// Constructors

	/** default constructor */
	public AbstractTSpeedCase() {
	}

	/** full constructor */
	public AbstractTSpeedCase(Float maxSpeed, Long cxTime, String deviceId,
			Date crtdate, String crtman) {
		this.maxSpeed = maxSpeed;
		this.cxTime = cxTime;
		this.deviceId = deviceId;
		this.crtdate = crtdate;
		this.crtman = crtman;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Float getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(Float maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	public Long getCxTime() {
		return this.cxTime;
	}

	public void setCxTime(Long cxTime) {
		this.cxTime = cxTime;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getCrtdate() {
		return this.crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public String getCrtman() {
		return this.crtman;
	}

	public void setCrtman(String crtman) {
		this.crtman = crtman;
	}

}