package com.autonavi.directl.bean;

import java.util.Date;

/**
 * AbstractTArea generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTArea implements java.io.Serializable {

	// Fields

	private Long id;

	private String name;

	private String xy;

	private String beginDate;

	private String endDate;

	private String epCode;

	private String deviceId;

	private String type;

	private Date createdate;

	private String createman;

	// Constructors

	/** default constructor */
	public AbstractTArea() {
	}

	/** full constructor */
	public AbstractTArea(String name, String xy, String beginDate,
			String endDate, String epCode, String deviceId, String type,
			Date createdate, String createman) {
		this.name = name;
		this.xy = xy;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.epCode = epCode;
		this.deviceId = deviceId;
		this.type = type;
		this.createdate = createdate;
		this.createman = createman;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getXy() {
		return this.xy;
	}

	public void setXy(String xy) {
		this.xy = xy;
	}

	public String getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(String beginDate) {
		this.beginDate = beginDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public String getEpCode() {
		return this.epCode;
	}

	public void setEpCode(String epCode) {
		this.epCode = epCode;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public String getCreateman() {
		return this.createman;
	}

	public void setCreateman(String createman) {
		this.createman = createman;
	}

}