package com.autonavi.directl.bean;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TArea generated by MyEclipse Persistence Tools
 */
public class TArea extends AbstractTArea implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public TArea() {
	}

	/** full constructor */
	public TArea(String name, String xy, String beginDate, String endDate,
			String epCode, String deviceId, String type, Date createdate,
			String createman) {
		super(name, xy, beginDate, endDate, epCode, deviceId, type, createdate,
				createman);
	}

}
