package com.autonavi.directl.bean;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TSpeedCase generated by MyEclipse Persistence Tools
 */
public class TSpeedCase extends AbstractTSpeedCase implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TSpeedCase() {
	}

	/** full constructor */
	public TSpeedCase(Float maxSpeed, Long cxTime, String deviceId,
			Date crtdate, String crtman) {
		super(maxSpeed, cxTime, deviceId, crtdate, crtman);
	}

}
