package com.autonavi.lbsgateway.service;

import java.util.ArrayList;

import com.autonavi.directl.base.TerminalInfo;
//Generated by MyEclipse

public interface ICommonGatewayService {
 	 
	 public boolean isOnLine(String simcard);
	
	 public String[]  getAllOnlineTerminals();
	
	 public ArrayList getAllOnlineTerms();
	
}