package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTCitytrafficinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTCitytrafficinfo  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String sp;
     private String contents;
     private String intersection;
     private Long liftingtime;
     private Float longitude;
     private Float latitude;
     private Date receivetime;
     private String flag;
     private String dirction;
     private Date modifytiem;


    // Constructors

    /** default constructor */
    public AbstractTCitytrafficinfo() {
    }

    
    /** full constructor */
    public AbstractTCitytrafficinfo(String sp, String contents, String intersection, Long liftingtime, Float longitude, Float latitude, Date receivetime, String flag,String dirction, Date modifytiem) {
        this.sp = sp;
        this.contents = contents;
        this.intersection = intersection;
        this.liftingtime = liftingtime;
        this.longitude = longitude;
        this.latitude = latitude;
        this.receivetime = receivetime;
        this.flag = flag;
        this.dirction = dirction;
        this.modifytiem = modifytiem;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSp() {
        return this.sp;
    }
    
    public void setSp(String sp) {
        this.sp = sp;
    }

    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }

    public String getIntersection() {
        return this.intersection;
    }
    
    public void setIntersection(String intersection) {
        this.intersection = intersection;
    }

    public Long getLiftingtime() {
        return this.liftingtime;
    }
    
    public void setLiftingtime(Long liftingtime) {
        this.liftingtime = liftingtime;
    }

    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public Date getReceivetime() {
        return this.receivetime;
    }
    
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    public Date getModifytiem() {
        return this.modifytiem;
    }
    
    public void setModifytiem(Date modifytiem) {
        this.modifytiem = modifytiem;
    }


	public String getDirction() {
		return dirction;
	}


	public void setDirction(String dirction) {
		this.dirction = dirction;
	}
}
   