package com.sosgps.wzt.orm;



/**
 * AbstractShandongUnusedReport generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongUnusedReport  implements java.io.Serializable {


    // Fields    

     private ShandongUnusedReportId id;


    // Constructors

    /** default constructor */
    public AbstractShandongUnusedReport() {
    }

    

   
    // Property accessors

    public ShandongUnusedReportId getId() {
        return this.id;
    }
    
    public void setId(ShandongUnusedReportId id) {
        this.id = id;
    }
   








}