package com.sosgps.wzt.orm;



/**
 * AbstractRefTermVirgroup generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRefTermVirgroup  implements java.io.Serializable {


    // Fields    

     private Long id;
     private TVirtualGroup TVirtualGroup;
     private TTerminal TTerminal;


    // Constructors

    /** default constructor */
    public AbstractRefTermVirgroup() {
    }

    
    /** full constructor */
    public AbstractRefTermVirgroup(TVirtualGroup TVirtualGroup, TTerminal TTerminal) {
        this.TVirtualGroup = TVirtualGroup;
        this.TTerminal = TTerminal;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public TVirtualGroup getTVirtualGroup() {
        return this.TVirtualGroup;
    }
    
    public void setTVirtualGroup(TVirtualGroup TVirtualGroup) {
        this.TVirtualGroup = TVirtualGroup;
    }

    public TTerminal getTTerminal() {
        return this.TTerminal;
    }
    
    public void setTTerminal(TTerminal TTerminal) {
        this.TTerminal = TTerminal;
    }
   








}