package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTMessage generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTMessage  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String sender;
     private String receiver;
     private String content;
     private String msgType;
     private Date createdate;
     private String createman;


    // Constructors

    /** default constructor */
    public AbstractTMessage() {
    }

    
    /** full constructor */
    public AbstractTMessage(String sender, String receiver, String content, String msgType, Date createdate, String createman) {
        this.sender = sender;
        this.receiver = receiver;
        this.content = content;
        this.msgType = msgType;
        this.createdate = createdate;
        this.createman = createman;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSender() {
        return this.sender;
    }
    
    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getReceiver() {
        return this.receiver;
    }
    
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getMsgType() {
        return this.msgType;
    }
    
    public void setMsgType(String msgType) {
        this.msgType = msgType;
    }

    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public String getCreateman() {
        return this.createman;
    }
    
    public void setCreateman(String createman) {
        this.createman = createman;
    }
   








}