package com.sosgps.wzt.orm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractTTerminal generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTTerminal implements java.io.Serializable {

	// Fields

	private String deviceId;
	private TEntTermtype TEntTermtype;
	private String termName;
	private String imgUrl;
	private Long suiteId;
	private String entCode;
	private String simcard;
	private String oemCode;
	private String driverNumber;
	private String locateType;
	private Long carTypeId;
	private String isAllocate;
	private String subCompany;
	private Date crtdate;
	private Long usageFlag;
	private Date outdate;

	private String startTime;
	private String endTime;
	private Long getherInterval;
	private String vehicleNumber;
	private String vehicleType;
	private Long oilSpeedLimit;
	private Long speedAlarmLimit;
	private Long speedAlarmLast;
	private String holdAlarmFlag;
	private String province;
	private String city;
	private String termdesc;
	private Long week;
	private Long carTypeInfoId;
	private Date expirationTime;
	private Long expirationFlag;
	private String imsi;

	public String getImsi() {
		return imsi;
	}

	public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	public Long getCarTypeInfoId() {
		return carTypeInfoId;
	}

	public void setCarTypeInfoId(Long carTypeInfoId) {
		this.carTypeInfoId = carTypeInfoId;
	}

	public Long getWeek() {
		return week;
	}

	public void setWeek(Long week) {
		this.week = week;
	}

	private Set TLocrecords = new HashSet(0);
	private Set TMutiMediums = new HashSet(0);
	private Set TLastLocrecords = new HashSet(0);
	private Set TInactiveAlarmLocs = new HashSet(0);
	private Set refTermGroups = new HashSet(0);
	private Set TStructionses = new HashSet(0);
	private Set TSpeedAlarmLocs = new HashSet(0);
	private Set TAreaLocrecords = new HashSet(0);
	private Set refTermAttrules = new HashSet(0);
	private Set refTermSimrules = new HashSet(0);
	private Set refTermVirgroups = new HashSet(0);
	private Set refTermAreaalarms = new HashSet(0);
	private Set refTermPois = new HashSet(0);
	private Set vehicleMsg = new HashSet(0);

	// Constructors

	public Set getVehicleMsg() {
		return vehicleMsg;
	}

	public void setVehicleMsg(Set vehicleMsg) {
		this.vehicleMsg = vehicleMsg;
	}

	public Set getRefTermAttrules() {
		return refTermAttrules;
	}

	public void setRefTermAttrules(Set refTermAttrules) {
		this.refTermAttrules = refTermAttrules;
	}

	public Set getRefTermSimrules() {
		return refTermSimrules;
	}

	public void setRefTermSimrules(Set refTermSimrules) {
		this.refTermSimrules = refTermSimrules;
	}

	/** default constructor */
	public AbstractTTerminal() {
	}

	/** minimal constructor */
	public AbstractTTerminal(String termName) {
		this.termName = termName;
	}

	/** full constructor 
	 * @param refTermAreaalarms */
	public AbstractTTerminal(TEntTermtype TEntTermtype, String termName,
			String imgUrl, Long suiteId, String entCode, String simcard,
			String oemCode, String driverNumber, String locateType,
			Long carTypeId, String isAllocate, String subCompany,
			Set TLocrecords, Set TMutiMediums, Set TLastLocrecords,
			Set TInactiveAlarmLocs, Set refTermGroups, Set TStructionses,
			Set TSpeedAlarmLocs, Set TAreaLocrecords, Set refTermAttrules,
			Set refTermSimrules, Set refTermVirgroups, Set refTermAreaalarms, String imsi) {
		this.TEntTermtype = TEntTermtype;
		this.termName = termName;
		this.imgUrl = imgUrl;
		this.suiteId = suiteId;
		this.entCode = entCode;
		this.simcard = simcard;
		this.oemCode = oemCode;
		this.driverNumber = driverNumber;
		this.locateType = locateType;
		this.carTypeId = carTypeId;
		this.isAllocate = isAllocate;
		this.subCompany = subCompany;
		this.TLocrecords = TLocrecords;
		this.TMutiMediums = TMutiMediums;
		this.TLastLocrecords = TLastLocrecords;
		this.TInactiveAlarmLocs = TInactiveAlarmLocs;
		this.refTermGroups = refTermGroups;
		this.TStructionses = TStructionses;
		this.TSpeedAlarmLocs = TSpeedAlarmLocs;
		this.TAreaLocrecords = TAreaLocrecords;
		this.refTermAttrules = refTermAttrules;
		this.refTermSimrules = refTermSimrules;
		this.refTermVirgroups = refTermVirgroups;
		this.refTermAreaalarms = refTermAreaalarms;
		this.imsi = imsi;
	}

	// Property accessors

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public TEntTermtype getTEntTermtype() {
		return this.TEntTermtype;
	}

	public void setTEntTermtype(TEntTermtype TEntTermtype) {
		this.TEntTermtype = TEntTermtype;
	}

	public String getTermName() {
		return this.termName;
	}

	public void setTermName(String termName) {
		this.termName = termName;
	}

	public String getImgUrl() {
		return this.imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public Long getSuiteId() {
		return this.suiteId;
	}

	public void setSuiteId(Long suiteId) {
		this.suiteId = suiteId;
	}

	public String getEntCode() {
		return this.entCode;
	}

	public void setEntCode(String entCode) {
		this.entCode = entCode;
	}

	public String getSimcard() {
		return this.simcard;
	}

	public void setSimcard(String simcard) {
		this.simcard = simcard;
	}

	public Set getTLocrecords() {
		return this.TLocrecords;
	}

	public void setTLocrecords(Set TLocrecords) {
		this.TLocrecords = TLocrecords;
	}

	public Set getTMutiMediums() {
		return this.TMutiMediums;
	}

	public void setTMutiMediums(Set TMutiMediums) {
		this.TMutiMediums = TMutiMediums;
	}

	public Set getTLastLocrecords() {
		return this.TLastLocrecords;
	}

	public void setTLastLocrecords(Set TLastLocrecords) {
		this.TLastLocrecords = TLastLocrecords;
	}

	public Set getTInactiveAlarmLocs() {
		return this.TInactiveAlarmLocs;
	}

	public void setTInactiveAlarmLocs(Set TInactiveAlarmLocs) {
		this.TInactiveAlarmLocs = TInactiveAlarmLocs;
	}

	public Set getRefTermGroups() {
		return this.refTermGroups;
	}

	public void setRefTermGroups(Set refTermGroups) {
		this.refTermGroups = refTermGroups;
	}

	public Set getTStructionses() {
		return this.TStructionses;
	}

	public void setTStructionses(Set TStructionses) {
		this.TStructionses = TStructionses;
	}

	public Set getTSpeedAlarmLocs() {
		return this.TSpeedAlarmLocs;
	}

	public void setTSpeedAlarmLocs(Set TSpeedAlarmLocs) {
		this.TSpeedAlarmLocs = TSpeedAlarmLocs;
	}

	public Set getTAreaLocrecords() {
		return this.TAreaLocrecords;
	}

	public void setTAreaLocrecords(Set TAreaLocrecords) {
		this.TAreaLocrecords = TAreaLocrecords;
	}

	public String getOemCode() {
		return this.oemCode;
	}

	public void setOemCode(String oemCode) {
		this.oemCode = oemCode;
	}

	public String getDriverNumber() {
		return this.driverNumber;
	}

	public void setDriverNumber(String driverNumber) {
		this.driverNumber = driverNumber;
	}

	public String getLocateType() {
		return this.locateType;
	}

	public void setLocateType(String locateType) {
		this.locateType = locateType;
	}

	public Long getCarTypeId() {
		return this.carTypeId;
	}

	public void setCarTypeId(Long carTypeId) {
		this.carTypeId = carTypeId;
	}

	public String getIsAllocate() {
		return this.isAllocate;
	}

	public void setIsAllocate(String isAllocate) {
		this.isAllocate = isAllocate;
	}

	public String getSubCompany() {
		return this.subCompany;
	}

	public void setSubCompany(String subCompany) {
		this.subCompany = subCompany;
	}

	public Date getCrtdate() {
		return crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public Long getUsageFlag() {
		return usageFlag;
	}

	public void setUsageFlag(Long usageFlag) {
		this.usageFlag = usageFlag;
	}

	public Date getOutdate() {
		return outdate;
	}

	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	public Set getRefTermVirgroups() {
		return refTermVirgroups;
	}

	public void setRefTermVirgroups(Set refTermVirgroups) {
		this.refTermVirgroups = refTermVirgroups;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public Long getGetherInterval() {
		return getherInterval;
	}

	public void setGetherInterval(Long getherInterval) {
		this.getherInterval = getherInterval;
	}

	public String getVehicleNumber() {
		return vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public String getVehicleType() {
		return vehicleType;
	}

	public void setVehicleType(String vehicleType) {
		this.vehicleType = vehicleType;
	}

	public Long getOilSpeedLimit() {
		return oilSpeedLimit;
	}

	public void setOilSpeedLimit(Long oilSpeedLimit) {
		this.oilSpeedLimit = oilSpeedLimit;
	}

	public Long getSpeedAlarmLimit() {
		return speedAlarmLimit;
	}

	public void setSpeedAlarmLimit(Long speedAlarmLimit) {
		this.speedAlarmLimit = speedAlarmLimit;
	}

	public Long getSpeedAlarmLast() {
		return speedAlarmLast;
	}

	public void setSpeedAlarmLast(Long speedAlarmLast) {
		this.speedAlarmLast = speedAlarmLast;
	}

	public String getHoldAlarmFlag() {
		return holdAlarmFlag;
	}

	public void setHoldAlarmFlag(String holdAlarmFlag) {
		this.holdAlarmFlag = holdAlarmFlag;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getTermdesc() {
		return termdesc;
	}

	public void setTermdesc(String termdesc) {
		this.termdesc = termdesc;
	}
	
	public Set getRefTermAreaalarms() {
		return this.refTermAreaalarms;
	}

	public void setRefTermAreaalarms(Set refTermAreaalarms) {
		this.refTermAreaalarms = refTermAreaalarms;
	}

	public Set getRefTermPois() {
		return refTermPois;
	}

	public void setRefTermPois(Set refTermPois) {
		this.refTermPois = refTermPois;
	}
	public Date getExpirationTime() {
		return expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

	public Long getExpirationFlag() {
		return expirationFlag;
	}

	public void setExpirationFlag(Long expirationFlag) {
		this.expirationFlag = expirationFlag;
	}

}