package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTLoginLog generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTLoginLog  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Long userId;
     private String userName;
     private String empCode;
     private String accessIp;
     private Date loginTime;
     private String loginDesc;
     private Long result;


    // Constructors

    /** default constructor */
    public AbstractTLoginLog() {
    }

	/** minimal constructor */
    public AbstractTLoginLog(Long userId, String userName, String empCode, String accessIp, Long result) {
        this.userId = userId;
        this.userName = userName;
        this.empCode = empCode;
        this.accessIp = accessIp;
        this.result = result;
    }
    
    /** full constructor */
    public AbstractTLoginLog(Long userId, String userName, String empCode, String accessIp, Date loginTime, String loginDesc, Long result) {
        this.userId = userId;
        this.userName = userName;
        this.empCode = empCode;
        this.accessIp = accessIp;
        this.loginTime = loginTime;
        this.loginDesc = loginDesc;
        this.result = result;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


    public String getAccessIp() {
        return this.accessIp;
    }
    
    public void setAccessIp(String accessIp) {
        this.accessIp = accessIp;
    }

    public Date getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginDesc() {
        return this.loginDesc;
    }
    
    public void setLoginDesc(String loginDesc) {
        this.loginDesc = loginDesc;
    }

    public Long getResult() {
        return this.result;
    }
    
    public void setResult(Long result) {
        this.result = result;
    }

	public String getEmpCode() {
		return empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}
   








}