package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTFreq generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTFreq implements java.io.Serializable {

	// Fields

	private Long id;

	private String value;

	private String deviceId;

	private Date crtdate;

	private String crtman;

	// Constructors

	/** default constructor */
	public AbstractTFreq() {
	}

	/** full constructor */
	public AbstractTFreq(String value, String deviceId, Date crtdate,
			String crtman) {
		this.value = value;
		this.deviceId = deviceId;
		this.crtdate = crtdate;
		this.crtman = crtman;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getCrtdate() {
		return this.crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public String getCrtman() {
		return this.crtman;
	}

	public void setCrtman(String crtman) {
		this.crtman = crtman;
	}

}