package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTLianxuxingshiTj generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTLianxuxingshiTj implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private Date startTime;

	private Date endTime;

	private Long continueTime;

	// Constructors

	/** default constructor */
	public AbstractTLianxuxingshiTj() {
	}

	/** full constructor */
	public AbstractTLianxuxingshiTj(String deviceId, Date startTime,
			Date endTime, Long continueTime) {
		this.deviceId = deviceId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.continueTime = continueTime;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Long getContinueTime() {
		return this.continueTime;
	}

	public void setContinueTime(Long continueTime) {
		this.continueTime = continueTime;
	}

}