package com.sosgps.wzt.orm;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractTTermGroup generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTTermGroup implements java.io.Serializable {

	// Fields

	private Long id;
	private TEnt TEnt;
	private String groupName;
	private Long parentId;
	private Long groupSort;

	private String startTime;
	private String endTime;
	private String groupStatus;
	private Long week;

	public Long getWeek() {
		return week;
	}

	public void setWeek(Long week) {
		this.week = week;
	}

	private Set refUserTgroups = new HashSet(0);
	private Set refTermGroups = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractTTermGroup() {
	}

	/** minimal constructor */
	public AbstractTTermGroup(String groupName, Long parentId, Long groupSort) {
		this.groupName = groupName;
		this.parentId = parentId;
		this.groupSort = groupSort;
	}

	/** full constructor */
	public AbstractTTermGroup(TEnt TEnt, String groupName, Long parentId,
			Long groupSort, Set refUserTgroups, Set refTermGroups) {
		this.TEnt = TEnt;
		this.groupName = groupName;
		this.parentId = parentId;
		this.groupSort = groupSort;
		this.refUserTgroups = refUserTgroups;
		this.refTermGroups = refTermGroups;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TEnt getTEnt() {
		return this.TEnt;
	}

	public void setTEnt(TEnt TEnt) {
		this.TEnt = TEnt;
	}

	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	public Long getParentId() {
		return this.parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getGroupSort() {
		return this.groupSort;
	}

	public void setGroupSort(Long groupSort) {
		this.groupSort = groupSort;
	}

	public Set getRefUserTgroups() {
		return this.refUserTgroups;
	}

	public void setRefUserTgroups(Set refUserTgroups) {
		this.refUserTgroups = refUserTgroups;
	}

	public Set getRefTermGroups() {
		return this.refTermGroups;
	}

	public void setRefTermGroups(Set refTermGroups) {
		this.refTermGroups = refTermGroups;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getGroupStatus() {
		return groupStatus;
	}

	public void setGroupStatus(String groupStatus) {
		this.groupStatus = groupStatus;
	}

}