package com.sosgps.wzt.orm;



/**
 * AbstractTDictItem generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTDictItem  implements java.io.Serializable {


    // Fields    

     private Long id;
     private TDict TDict;
     private String itemName;
     private String itemCode;
     private String dictCode;
     private String usageFlag;


    // Constructors

    /** default constructor */
    public AbstractTDictItem() {
    }

	/** minimal constructor */
    public AbstractTDictItem(TDict TDict, String itemName, String itemCode, String dictCode) {
        this.TDict = TDict;
        this.itemName = itemName;
        this.itemCode = itemCode;
        this.dictCode = dictCode;
    }
    
    /** full constructor */
    public AbstractTDictItem(TDict TDict, String itemName, String itemCode, String dictCode, String usageFlag) {
        this.TDict = TDict;
        this.itemName = itemName;
        this.itemCode = itemCode;
        this.dictCode = dictCode;
        this.usageFlag = usageFlag;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public TDict getTDict() {
        return this.TDict;
    }
    
    public void setTDict(TDict TDict) {
        this.TDict = TDict;
    }

    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemCode() {
        return this.itemCode;
    }
    
    public void setItemCode(String itemCode) {
        this.itemCode = itemCode;
    }

    public String getDictCode() {
        return this.dictCode;
    }
    
    public void setDictCode(String dictCode) {
        this.dictCode = dictCode;
    }

    public String getUsageFlag() {
        return this.usageFlag;
    }
    
    public void setUsageFlag(String usageFlag) {
        this.usageFlag = usageFlag;
    }
   








}