package com.sosgps.wzt.orm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTArea generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTArea  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String name;
     private String xy;
     private String epCode;
     private Date createdate;
     private String createman;
     private String flag;
     private String areaType;
     
//     private String beginDate;
//     private String endDate;
//     private String deviceId;
//     private String type;
//     private Long lineStyle;
//     private Long lineColor;
//     private Long lineWidth;
//     private Long lineAlpha;
//     private Long fillColor;
//     private Long fillStyle;
//     private Long fillAlpha;
//     private Long fillShow;
     private Set refTermAreaalarms = new HashSet(0);

    // Constructors

    /** default constructor */
    public AbstractTArea() {
    }

    
    /** full constructor */
    public AbstractTArea(String name, String xy, String epCode, Date createdate, String createman, String flag, String areaType, Set refTermAreaalarms) {
        this.name = name;
        this.xy = xy;
        this.epCode = epCode;
        this.createdate = createdate;
        this.createman = createman;
        this.flag = flag;
        this.areaType = areaType;
        this.refTermAreaalarms = refTermAreaalarms;
    }
//    public AbstractTArea(String name, String xy, String beginDate, String endDate, String epCode, String deviceId, String type, Date createdate, String createman, String flag, String areaType, Long lineStyle, Long lineColor, Long lineWidth, Long lineAlpha, Long fillColor, Long fillStyle, Long fillAlpha, Long fillShow, Set refTermAreaalarms) {
//        this.name = name;
//        this.xy = xy;
//        this.beginDate = beginDate;
//        this.endDate = endDate;
//        this.epCode = epCode;
//        this.deviceId = deviceId;
//        this.type = type;
//        this.createdate = createdate;
//        this.createman = createman;
//        this.flag = flag;
//        this.areaType = areaType;
//        this.lineStyle = lineStyle;
//        this.lineColor = lineColor;
//        this.lineWidth = lineWidth;
//        this.lineAlpha = lineAlpha;
//        this.fillColor = fillColor;
//        this.fillStyle = fillStyle;
//        this.fillAlpha = fillAlpha;
//        this.fillShow = fillShow;
//        this.refTermAreaalarms = refTermAreaalarms;
//    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getXy() {
        return this.xy;
    }
    
    public void setXy(String xy) {
        this.xy = xy;
    }    

    public String getEpCode() {
        return this.epCode;
    }
    
    public void setEpCode(String epCode) {
        this.epCode = epCode;
    }
    

    public Date getCreatedate() {
        return this.createdate;
    }
    
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    public String getCreateman() {
        return this.createman;
    }
    
    public void setCreateman(String createman) {
        this.createman = createman;
    }

    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    public String getAreaType() {
        return this.areaType;
    }
    
    public void setAreaType(String areaType) {
        this.areaType = areaType;
    }
    /**
    public String getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    public String getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Long getLineStyle() {
        return this.lineStyle;
    }
    
    public void setLineStyle(Long lineStyle) {
        this.lineStyle = lineStyle;
    }

    public Long getLineColor() {
        return this.lineColor;
    }
    
    public void setLineColor(Long lineColor) {
        this.lineColor = lineColor;
    }

    public Long getLineWidth() {
        return this.lineWidth;
    }
    
    public void setLineWidth(Long lineWidth) {
        this.lineWidth = lineWidth;
    }

    public Long getLineAlpha() {
        return this.lineAlpha;
    }
    
    public void setLineAlpha(Long lineAlpha) {
        this.lineAlpha = lineAlpha;
    }

    public Long getFillColor() {
        return this.fillColor;
    }
    
    public void setFillColor(Long fillColor) {
        this.fillColor = fillColor;
    }

    public Long getFillStyle() {
        return this.fillStyle;
    }
    
    public void setFillStyle(Long fillStyle) {
        this.fillStyle = fillStyle;
    }

    public Long getFillAlpha() {
        return this.fillAlpha;
    }
    
    public void setFillAlpha(Long fillAlpha) {
        this.fillAlpha = fillAlpha;
    }

    public Long getFillShow() {
        return this.fillShow;
    }
    
    public void setFillShow(Long fillShow) {
        this.fillShow = fillShow;
    }
   */
    public Set getRefTermAreaalarms() {
		return this.refTermAreaalarms;
	}

	public void setRefTermAreaalarms(Set refTermAreaalarms) {
		this.refTermAreaalarms = refTermAreaalarms;
	}







}