package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractShandongSmsWait generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongSmsWait  implements java.io.Serializable {


    // Fields    

     private String waitId;
     private Date createTime;
     private Date sendTime;
     private Date validTime;
     private String longid;
     private String desmobile;
     private String content;
     private Long contentType;
     private Long retry;
     private Long gwkind;
     private Long report;
     private String hwyid;
     private Long messagetype;


    // Constructors

    /** default constructor */
    public AbstractShandongSmsWait() {
    }

	/** minimal constructor */
    public AbstractShandongSmsWait(Date createTime, Date sendTime, Date validTime, String desmobile, String content, Long contentType, Long retry, Long gwkind, Long report) {
        this.createTime = createTime;
        this.sendTime = sendTime;
        this.validTime = validTime;
        this.desmobile = desmobile;
        this.content = content;
        this.contentType = contentType;
        this.retry = retry;
        this.gwkind = gwkind;
        this.report = report;
    }
    
    /** full constructor */
    public AbstractShandongSmsWait(Date createTime, Date sendTime, Date validTime, String longid, String desmobile, String content, Long contentType, Long retry, Long gwkind, Long report, String hwyid, Long messagetype) {
        this.createTime = createTime;
        this.sendTime = sendTime;
        this.validTime = validTime;
        this.longid = longid;
        this.desmobile = desmobile;
        this.content = content;
        this.contentType = contentType;
        this.retry = retry;
        this.gwkind = gwkind;
        this.report = report;
        this.hwyid = hwyid;
        this.messagetype = messagetype;
    }

   
    // Property accessors

    public String getWaitId() {
        return this.waitId;
    }
    
    public void setWaitId(String waitId) {
        this.waitId = waitId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getSendTime() {
        return this.sendTime;
    }
    
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    public Date getValidTime() {
        return this.validTime;
    }
    
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    public String getLongid() {
        return this.longid;
    }
    
    public void setLongid(String longid) {
        this.longid = longid;
    }

    public String getDesmobile() {
        return this.desmobile;
    }
    
    public void setDesmobile(String desmobile) {
        this.desmobile = desmobile;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public Long getContentType() {
        return this.contentType;
    }
    
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    public Long getRetry() {
        return this.retry;
    }
    
    public void setRetry(Long retry) {
        this.retry = retry;
    }

    public Long getGwkind() {
        return this.gwkind;
    }
    
    public void setGwkind(Long gwkind) {
        this.gwkind = gwkind;
    }

    public Long getReport() {
        return this.report;
    }
    
    public void setReport(Long report) {
        this.report = report;
    }

    public String getHwyid() {
        return this.hwyid;
    }
    
    public void setHwyid(String hwyid) {
        this.hwyid = hwyid;
    }

    public Long getMessagetype() {
        return this.messagetype;
    }
    
    public void setMessagetype(Long messagetype) {
        this.messagetype = messagetype;
    }
   








}