package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTLastLocrecord generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTLastLocrecord implements java.io.Serializable {

	// Fields

	private Long id;

	private Float latitude;

	private Float longitude;

	private String jmx;

	private String jmy;

	private Float speed;

	private Float direction;

	private Float height;

	private Float distance;

	private Float statlliteNum;

	private String deviceId;

	private Date gpstime;

	private Date inputdate;

	private String locateType;

	private String hasInvalidData;
	
	private Date lastTime;

	private String accStatus;
	private Float temperature;
	// Constructors

	public String getLocateType() {
		return this.locateType;
	}

	public void setLocateType(String locateType) {
		this.locateType = locateType;
	}

	/** default constructor */
	public AbstractTLastLocrecord() {
	}

	/** full constructor */
	public AbstractTLastLocrecord(Float latitude, Float longitude, String jmx,
			String jmy, Float speed, Float direction, Float height,
			Float distance, Float statlliteNum, String deviceId, Date gpstime,
			Date inputdate, String locateType) {
		this.latitude = latitude;
		this.longitude = longitude;
		this.jmx = jmx;
		this.jmy = jmy;
		this.speed = speed;
		this.direction = direction;
		this.height = height;
		this.distance = distance;
		this.statlliteNum = statlliteNum;
		this.deviceId = deviceId;
		this.gpstime = gpstime;
		this.inputdate = inputdate;
		this.locateType = locateType;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public String getJmx() {
		return this.jmx;
	}

	public void setJmx(String jmx) {
		this.jmx = jmx;
	}

	public String getJmy() {
		return this.jmy;
	}

	public void setJmy(String jmy) {
		this.jmy = jmy;
	}

	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}

	public Float getDirection() {
		return this.direction;
	}

	public void setDirection(Float direction) {
		this.direction = direction;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	public Float getStatlliteNum() {
		return this.statlliteNum;
	}

	public void setStatlliteNum(Float statlliteNum) {
		this.statlliteNum = statlliteNum;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getGpstime() {
		return this.gpstime;
	}

	public void setGpstime(Date gpstime) {
		this.gpstime = gpstime;
	}

	public Date getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(Date inputdate) {
		this.inputdate = inputdate;
	}

	public String getHasInvalidData() {
		return hasInvalidData;
	}

	public void setHasInvalidData(String hasInvalidData) {
		this.hasInvalidData = hasInvalidData;
	}

	public Date getLastTime() {
		return lastTime;
	}

	public void setLastTime(Date lastTime) {
		this.lastTime = lastTime;
	}
	
	public String getAccStatus() {
		return accStatus;
	}

	public void setAccStatus(String accStatus) {
		this.accStatus = accStatus;
	}

	public Float getTemperature() {
		return temperature;
	}

	public void setTemperature(Float temperature) {
		this.temperature = temperature;
	}
}