package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTAlarmTjYear generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTAlarmTjYear  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String deviceId;
     private Long speedAlarm;
     private Long inactiveAlarm;
     private Long areaAlarm;
     private Long lineAlarm;
     private Date tjdate;
     private Long emerAlarm;
     private Long callRecord;
     private Long shortmessRecord;


    // Constructors

    /** default constructor */
    public AbstractTAlarmTjYear() {
    }

    
    /** full constructor */
    public AbstractTAlarmTjYear(String deviceId, Long speedAlarm, Long inactiveAlarm, Long areaAlarm, Long lineAlarm, Date tjdate, Long emerAlarm, Long callRecord, Long shortmessRecord) {
        this.deviceId = deviceId;
        this.speedAlarm = speedAlarm;
        this.inactiveAlarm = inactiveAlarm;
        this.areaAlarm = areaAlarm;
        this.lineAlarm = lineAlarm;
        this.tjdate = tjdate;
        this.emerAlarm = emerAlarm;
        this.callRecord = callRecord;
        this.shortmessRecord = shortmessRecord;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public Long getSpeedAlarm() {
        return this.speedAlarm;
    }
    
    public void setSpeedAlarm(Long speedAlarm) {
        this.speedAlarm = speedAlarm;
    }

    public Long getInactiveAlarm() {
        return this.inactiveAlarm;
    }
    
    public void setInactiveAlarm(Long inactiveAlarm) {
        this.inactiveAlarm = inactiveAlarm;
    }

    public Long getAreaAlarm() {
        return this.areaAlarm;
    }
    
    public void setAreaAlarm(Long areaAlarm) {
        this.areaAlarm = areaAlarm;
    }

    public Long getLineAlarm() {
        return this.lineAlarm;
    }
    
    public void setLineAlarm(Long lineAlarm) {
        this.lineAlarm = lineAlarm;
    }

    public Date getTjdate() {
        return this.tjdate;
    }
    
    public void setTjdate(Date tjdate) {
        this.tjdate = tjdate;
    }

    public Long getEmerAlarm() {
        return this.emerAlarm;
    }
    
    public void setEmerAlarm(Long emerAlarm) {
        this.emerAlarm = emerAlarm;
    }

    public Long getCallRecord() {
        return this.callRecord;
    }
    
    public void setCallRecord(Long callRecord) {
        this.callRecord = callRecord;
    }

    public Long getShortmessRecord() {
        return this.shortmessRecord;
    }
    
    public void setShortmessRecord(Long shortmessRecord) {
        this.shortmessRecord = shortmessRecord;
    }
   








}