package com.sosgps.wzt.orm;



/**
 * AbstractRefUserTgroupId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRefUserTgroupId  implements java.io.Serializable {


    // Fields    

     private Long userId;
     private TTermGroup TTermGroup;


    // Constructors

    /** default constructor */
    public AbstractRefUserTgroupId() {
    }

	/** minimal constructor */
    public AbstractRefUserTgroupId(Long userId) {
        this.userId = userId;
    }
    
    /** full constructor */
    public AbstractRefUserTgroupId(Long userId, TTermGroup TTermGroup) {
        this.userId = userId;
        this.TTermGroup = TTermGroup;
    }

   
    // Property accessors

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public TTermGroup getTTermGroup() {
        return this.TTermGroup;
    }
    
    public void setTTermGroup(TTermGroup TTermGroup) {
        this.TTermGroup = TTermGroup;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractRefUserTgroupId) ) return false;
		 AbstractRefUserTgroupId castOther = ( AbstractRefUserTgroupId ) other; 
         
		 return ( (this.getUserId()==castOther.getUserId()) || ( this.getUserId()!=null && castOther.getUserId()!=null && this.getUserId().equals(castOther.getUserId()) ) )
 && ( (this.getTTermGroup()==castOther.getTTermGroup()) || ( this.getTTermGroup()!=null && castOther.getTTermGroup()!=null && this.getTTermGroup().equals(castOther.getTTermGroup()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserId() == null ? 0 : this.getUserId().hashCode() );
         result = 37 * result + ( getTTermGroup() == null ? 0 : this.getTTermGroup().hashCode() );
         return result;
   }   





}