package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractShandongSmsRecv generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongSmsRecv  implements java.io.Serializable {


    // Fields    

     private String recvId;
     private Date createTime;
     private Date validTime;
     private String srcmobile;
     private String longid;
     private Long contentType;
     private String content;


    // Constructors

    /** default constructor */
    public AbstractShandongSmsRecv() {
    }

	/** minimal constructor */
    public AbstractShandongSmsRecv(Date createTime, Date validTime, String srcmobile, Long contentType) {
        this.createTime = createTime;
        this.validTime = validTime;
        this.srcmobile = srcmobile;
        this.contentType = contentType;
    }
    
    /** full constructor */
    public AbstractShandongSmsRecv(Date createTime, Date validTime, String srcmobile, String longid, Long contentType, String content) {
        this.createTime = createTime;
        this.validTime = validTime;
        this.srcmobile = srcmobile;
        this.longid = longid;
        this.contentType = contentType;
        this.content = content;
    }

   
    // Property accessors

    public String getRecvId() {
        return this.recvId;
    }
    
    public void setRecvId(String recvId) {
        this.recvId = recvId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getValidTime() {
        return this.validTime;
    }
    
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    public String getSrcmobile() {
        return this.srcmobile;
    }
    
    public void setSrcmobile(String srcmobile) {
        this.srcmobile = srcmobile;
    }

    public String getLongid() {
        return this.longid;
    }
    
    public void setLongid(String longid) {
        this.longid = longid;
    }

    public Long getContentType() {
        return this.contentType;
    }
    
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
   








}