package com.sosgps.wzt.orm;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractTUser generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTUser implements java.io.Serializable {

	// Fields

	private Long id;
	private String userAccount;
	private String userPassword;
	private String createBy;
	private String createDate;
	private String usageFlag;
	private String empCode;
	private String userContact;
	private String limitedIp;
	private String isAreaAlarm;

	private String userName;
	private String province;
	private String city;
	private String controlPassword;

	private Set refUserRoles = new HashSet(0);

	// Constructors

	/** default constructor */
	public AbstractTUser() {
	}

	/** minimal constructor */
	public AbstractTUser(String userAccount, String userPassword,
			String createDate, String usageFlag) {
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.createDate = createDate;
		this.usageFlag = usageFlag;
	}

	/** full constructor */
	public AbstractTUser(String userAccount, String userPassword,
			String createBy, String createDate, String usageFlag,
			String empCode, Set refUserRoles) {
		this.userAccount = userAccount;
		this.userPassword = userPassword;
		this.createBy = createBy;
		this.createDate = createDate;
		this.usageFlag = usageFlag;
		this.empCode = empCode;
		this.refUserRoles = refUserRoles;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getUserAccount() {
		return this.userAccount;
	}

	public void setUserAccount(String userAccount) {
		this.userAccount = userAccount;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	public String getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(String createDate) {
		this.createDate = createDate;
	}

	public String getUsageFlag() {
		return this.usageFlag;
	}

	public void setUsageFlag(String usageFlag) {
		this.usageFlag = usageFlag;
	}

	public Set getRefUserRoles() {
		return this.refUserRoles;
	}

	public void setRefUserRoles(Set refUserRoles) {
		this.refUserRoles = refUserRoles;
	}

	public String getEmpCode() {
		return empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	public String getUserContact() {
		return userContact;
	}

	public void setUserContact(String userContact) {
		this.userContact = userContact;
	}

	public String getLimitedIp() {
		return limitedIp;
	}

	public void setLimitedIp(String limitedIp) {
		this.limitedIp = limitedIp;
	}

	public String getIsAreaAlarm() {
		return isAreaAlarm;
	}

	public void setIsAreaAlarm(String isAreaAlarm) {
		this.isAreaAlarm = isAreaAlarm;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getProvince() {
		return province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getControlPassword() {
		return controlPassword;
	}

	public void setControlPassword(String controlPassword) {
		this.controlPassword = controlPassword;
	}

}