package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTOptLog generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTOptLog  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Long userId;
     private String userName;
     private String empCode;
     private Date optTime;
     private String accessIp;
     private String optDesc;
     private String funFType;
     private String funCType;
     private Long result;


    // Constructors

    /** default constructor */
    public AbstractTOptLog() {
    }

    
    /** full constructor */
    public AbstractTOptLog(Long userId, String userName, String empCode, Date optTime, String accessIp, String optDesc, String funFType, String funCType, Long result) {
        this.userId = userId;
        this.userName = userName;
        this.empCode = empCode;
        this.optTime = optTime;
        this.accessIp = accessIp;
        this.optDesc = optDesc;
        this.funFType = funFType;
        this.funCType = funCType;
        this.result = result;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }


    public Date getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    public String getAccessIp() {
        return this.accessIp;
    }
    
    public void setAccessIp(String accessIp) {
        this.accessIp = accessIp;
    }

    public String getOptDesc() {
        return this.optDesc;
    }
    
    public void setOptDesc(String optDesc) {
        this.optDesc = optDesc;
    }

    public String getFunFType() {
        return this.funFType;
    }
    
    public void setFunFType(String funFType) {
        this.funFType = funFType;
    }

    public String getFunCType() {
        return this.funCType;
    }
    
    public void setFunCType(String funCType) {
        this.funCType = funCType;
    }

    public Long getResult() {
        return this.result;
    }
    
    public void setResult(Long result) {
        this.result = result;
    }


	public String getEmpCode() {
		return empCode;
	}


	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}
   








}