package com.sosgps.wzt.orm;



/**
 * AbstractRefUserRole generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRefUserRole  implements java.io.Serializable {


    // Fields    

     private Long id;
     private TRole TRole;
     private TUser TUser;


    // Constructors

    /** default constructor */
    public AbstractRefUserRole() {
    }

    
    /** full constructor */
    public AbstractRefUserRole(TRole TRole, TUser TUser) {
        this.TRole = TRole;
        this.TUser = TUser;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public TRole getTRole() {
        return this.TRole;
    }
    
    public void setTRole(TRole TRole) {
        this.TRole = TRole;
    }

    public TUser getTUser() {
        return this.TUser;
    }
    
    public void setTUser(TUser TUser) {
        this.TUser = TUser;
    }
   








}