package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractCarTypeInfo generated by MyEclipse Persistence Tools
 */

@SuppressWarnings("serial")
public abstract class AbstractCarTypeInfo implements java.io.Serializable {

	// Fields

	private Long id;

	private String typeName;

	private String iconPath;

	private String desction;

	private String enCode;

	private Long oilWear;

	private Long userId;

	private Long changeUserId;

	private Date crtdate;

	private Date changeDate;
	// Constructors

	/** default constructor */
	public AbstractCarTypeInfo() {
	}

	public Date getCrtdate() {
		return crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public Date getChangeDate() {
		return changeDate;
	}

	public void setChangeDate(Date changeDate) {
		this.changeDate = changeDate;
	}

	/** full constructor */
	public AbstractCarTypeInfo(String typeName, String iconPath,
			String desction, String enCode, Long oilWear, Long userId, 
			Long changeUserId, Date crtdate, Date changeDate) {
		this.typeName = typeName;
		this.iconPath = iconPath;
		this.desction = desction;
		this.enCode = enCode;
		this.oilWear = oilWear;
		this.userId = userId;
		this.changeUserId = changeUserId;
		this.crtdate = crtdate;
		this.changeDate = changeDate;
	}

	// Property accessors

	public Long getChangeUserId() {
		return changeUserId;
	}

	public void setChangeUserId(Long changeUserId) {
		this.changeUserId = changeUserId;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getOilWear() {
		return oilWear;
	}

	public void setOilWear(Long oilWear) {
		this.oilWear = oilWear;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public String getIconPath() {
		return this.iconPath;
	}

	public void setIconPath(String iconPath) {
		this.iconPath = iconPath;
	}

	public String getDesction() {
		return this.desction;
	}

	public void setDesction(String desction) {
		this.desction = desction;
	}

	public String getEnCode() {
		return this.enCode;
	}

	public void setEnCode(String enCode) {
		this.enCode = enCode;
	}

}