package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTSpeedAlarmLoc generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTSpeedAlarmLoc  implements java.io.Serializable {


    // Fields    

     private Long id;
     private TTerminal TTerminal;
     private Long longitude;
     private Long latitude;
     private Long jmx;
     private Long jmy;
     private Long speed;
     private Long direction;
     private Long height;
     private Long distance;
     private Long statlliteNum;
     private Date alarmTime;
     private Date inputdate;


    // Constructors

    /** default constructor */
    public AbstractTSpeedAlarmLoc() {
    }

    
    /** full constructor */
    public AbstractTSpeedAlarmLoc(TTerminal TTerminal, Long longitude, Long latitude, Long jmx, Long jmy, Long speed, Long direction, Long height, Long distance, Long statlliteNum, Date alarmTime, Date inputdate) {
        this.TTerminal = TTerminal;
        this.longitude = longitude;
        this.latitude = latitude;
        this.jmx = jmx;
        this.jmy = jmy;
        this.speed = speed;
        this.direction = direction;
        this.height = height;
        this.distance = distance;
        this.statlliteNum = statlliteNum;
        this.alarmTime = alarmTime;
        this.inputdate = inputdate;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public TTerminal getTTerminal() {
        return this.TTerminal;
    }
    
    public void setTTerminal(TTerminal TTerminal) {
        this.TTerminal = TTerminal;
    }

    public Long getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Long longitude) {
        this.longitude = longitude;
    }

    public Long getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Long latitude) {
        this.latitude = latitude;
    }

    public Long getJmx() {
        return this.jmx;
    }
    
    public void setJmx(Long jmx) {
        this.jmx = jmx;
    }

    public Long getJmy() {
        return this.jmy;
    }
    
    public void setJmy(Long jmy) {
        this.jmy = jmy;
    }

    public Long getSpeed() {
        return this.speed;
    }
    
    public void setSpeed(Long speed) {
        this.speed = speed;
    }

    public Long getDirection() {
        return this.direction;
    }
    
    public void setDirection(Long direction) {
        this.direction = direction;
    }

    public Long getHeight() {
        return this.height;
    }
    
    public void setHeight(Long height) {
        this.height = height;
    }

    public Long getDistance() {
        return this.distance;
    }
    
    public void setDistance(Long distance) {
        this.distance = distance;
    }

    public Long getStatlliteNum() {
        return this.statlliteNum;
    }
    
    public void setStatlliteNum(Long statlliteNum) {
        this.statlliteNum = statlliteNum;
    }

    public Date getAlarmTime() {
        return this.alarmTime;
    }
    
    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    public Date getInputdate() {
        return this.inputdate;
    }
    
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }
   








}