package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTAlarmShow generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTAlarmShow implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private String alarmType;

	private String alarmContent;

	private String flag;

	private Date alarmDate;

	private Date stopAlarmDate;

	private Long alarmId;

	// Constructors

	/** default constructor */
	public AbstractTAlarmShow() {
	}

	/** full constructor */
	public AbstractTAlarmShow(String deviceId, String alarmType,
			String alarmContent, String flag, Date alarmDate,
			Date stopAlarmDate, Long alarmId) {
		this.deviceId = deviceId;
		this.alarmType = alarmType;
		this.alarmContent = alarmContent;
		this.flag = flag;
		this.alarmDate = alarmDate;
		this.stopAlarmDate = stopAlarmDate;
		this.alarmId = alarmId;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getAlarmType() {
		return this.alarmType;
	}

	public void setAlarmType(String alarmType) {
		this.alarmType = alarmType;
	}

	public String getAlarmContent() {
		return this.alarmContent;
	}

	public void setAlarmContent(String alarmContent) {
		this.alarmContent = alarmContent;
	}

	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

	public Date getAlarmDate() {
		return this.alarmDate;
	}

	public void setAlarmDate(Date alarmDate) {
		this.alarmDate = alarmDate;
	}

	public Date getStopAlarmDate() {
		return this.stopAlarmDate;
	}

	public void setStopAlarmDate(Date stopAlarmDate) {
		this.stopAlarmDate = stopAlarmDate;
	}

	public Long getAlarmId() {
		return this.alarmId;
	}

	public void setAlarmId(Long alarmId) {
		this.alarmId = alarmId;
	}

}