package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractShandongLogRecv generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongLogRecv  implements java.io.Serializable {


    // Fields    

     private String logId;
     private Date createTime;
     private String srcmobile;
     private String longid;
     private Long contentType;
     private String content;
     private String createSubTime;

     private ShandongSmsRecv shandongSmsRecv;

    // Constructors

    /** default constructor */
    public AbstractShandongLogRecv() {
    }

	/** minimal constructor */
    public AbstractShandongLogRecv(Date createTime, String srcmobile, Long contentType, String createSubTime) {
        this.createTime = createTime;
        this.srcmobile = srcmobile;
        this.contentType = contentType;
        this.createSubTime = createSubTime;
    }
    
    /** full constructor */
    public AbstractShandongLogRecv(Date createTime, String srcmobile, String longid, Long contentType, String content, String createSubTime) {
        this.createTime = createTime;
        this.srcmobile = srcmobile;
        this.longid = longid;
        this.contentType = contentType;
        this.content = content;
        this.createSubTime = createSubTime;
    }

   
    // Property accessors

    public String getLogId() {
        return this.logId;
    }
    
    public void setLogId(String logId) {
        this.logId = logId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getSrcmobile() {
        return this.srcmobile;
    }
    
    public void setSrcmobile(String srcmobile) {
        this.srcmobile = srcmobile;
    }

    public String getLongid() {
        return this.longid;
    }
    
    public void setLongid(String longid) {
        this.longid = longid;
    }

    public Long getContentType() {
        return this.contentType;
    }
    
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getCreateSubTime() {
        return this.createSubTime;
    }
    
    public void setCreateSubTime(String createSubTime) {
        this.createSubTime = createSubTime;
    }

	public ShandongSmsRecv getShandongSmsRecv() {
		return shandongSmsRecv;
	}

	public void setShandongSmsRecv(ShandongSmsRecv shandongSmsRecv) {
		this.shandongSmsRecv = shandongSmsRecv;
	}
   








}