package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTBajuTask generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTBajuTask implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private String taskContent;

	private String state;

	private String type;

	private String reply;

	private Date crtdate;

	private String crtman;

	// Constructors

	/** default constructor */
	public AbstractTBajuTask() {
	}

	/** full constructor */
	public AbstractTBajuTask(String deviceId, String taskContent, String state,
			String type, String reply, Date crtdate, String crtman) {
		this.deviceId = deviceId;
		this.taskContent = taskContent;
		this.state = state;
		this.type = type;
		this.reply = reply;
		this.crtdate = crtdate;
		this.crtman = crtman;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getTaskContent() {
		return this.taskContent;
	}

	public void setTaskContent(String taskContent) {
		this.taskContent = taskContent;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getReply() {
		return this.reply;
	}

	public void setReply(String reply) {
		this.reply = reply;
	}

	public Date getCrtdate() {
		return this.crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public String getCrtman() {
		return this.crtman;
	}

	public void setCrtman(String crtman) {
		this.crtman = crtman;
	}

}