package com.sosgps.wzt.orm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTTerminalType generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTEntTermtype  implements java.io.Serializable {


    // Fields    

     private String typeCode;
     private String typeName;
     private Date inputdate;
     private String createman;
     private Set TTerminals = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTEntTermtype() {
    }

    
    /** full constructor */
    public AbstractTEntTermtype(String typeName, Date inputdate, String createman, Set TTerminals) {
        this.typeName = typeName;
        this.inputdate = inputdate;
        this.createman = createman;
        this.TTerminals = TTerminals;
    }

   
    // Property accessors

    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public String getTypeName() {
        return this.typeName;
    }
    
    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Date getInputdate() {
        return this.inputdate;
    }
    
    public void setInputdate(Date inputdate) {
        this.inputdate = inputdate;
    }

    public String getCreateman() {
        return this.createman;
    }
    
    public void setCreateman(String createman) {
        this.createman = createman;
    }

    public Set getTTerminals() {
        return this.TTerminals;
    }
    
    public void setTTerminals(Set TTerminals) {
        this.TTerminals = TTerminals;
    }
   








}