package com.sosgps.wzt.orm;

/**
 * AbstractTDistanceDay generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTTotalDistance implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String deviceId;

	private Float distance;

	private String empCode;
	
	private Float userId;

	// Constructors

	/** default constructor */
	public AbstractTTotalDistance() {
	}

	/** full constructor */
	public AbstractTTotalDistance(String deviceId, Float distance, String empCode, Float userId) {
		this.deviceId = deviceId;
		this.distance = distance;
		this.empCode = empCode;
		this.userId = userId;
	}

	// Property accessors

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	public String getEmpCode() {
		return empCode;
	}

	public void setEmpCode(String empCode) {
		this.empCode = empCode;
	}

	public Float getUserId() {
		return userId;
	}

	public void setUserId(Float userId) {
		this.userId = userId;
	}

}