package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractShandongLogSend generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongLogSend  implements java.io.Serializable {


    // Fields    

     private String logId;
     private Date createTime;
     private String longid;
     private String desmobile;
     private String content;
     private Long ecode;
     private Long rcode;
     private String sendid;
     private Date reptTime;
     private String createSubTime;
     private Long contentType;
     private Long gwkind;
     private String city;
     private String province;
     private String hwyid;
     private Long messagetype;


    // Constructors

    /** default constructor */
    public AbstractShandongLogSend() {
    }

	/** minimal constructor */
    public AbstractShandongLogSend(Date createTime, String desmobile, String content, Long ecode, Long rcode, String createSubTime, Long contentType, Long gwkind) {
        this.createTime = createTime;
        this.desmobile = desmobile;
        this.content = content;
        this.ecode = ecode;
        this.rcode = rcode;
        this.createSubTime = createSubTime;
        this.contentType = contentType;
        this.gwkind = gwkind;
    }
    
    /** full constructor */
    public AbstractShandongLogSend(Date createTime, String longid, String desmobile, String content, Long ecode, Long rcode, String sendid, Date reptTime, String createSubTime, Long contentType, Long gwkind, String city, String province, String hwyid, Long messagetype) {
        this.createTime = createTime;
        this.longid = longid;
        this.desmobile = desmobile;
        this.content = content;
        this.ecode = ecode;
        this.rcode = rcode;
        this.sendid = sendid;
        this.reptTime = reptTime;
        this.createSubTime = createSubTime;
        this.contentType = contentType;
        this.gwkind = gwkind;
        this.city = city;
        this.province = province;
        this.hwyid = hwyid;
        this.messagetype = messagetype;
    }

   
    // Property accessors

    public String getLogId() {
        return this.logId;
    }
    
    public void setLogId(String logId) {
        this.logId = logId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getLongid() {
        return this.longid;
    }
    
    public void setLongid(String longid) {
        this.longid = longid;
    }

    public String getDesmobile() {
        return this.desmobile;
    }
    
    public void setDesmobile(String desmobile) {
        this.desmobile = desmobile;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public Long getEcode() {
        return this.ecode;
    }
    
    public void setEcode(Long ecode) {
        this.ecode = ecode;
    }

    public Long getRcode() {
        return this.rcode;
    }
    
    public void setRcode(Long rcode) {
        this.rcode = rcode;
    }

    public String getSendid() {
        return this.sendid;
    }
    
    public void setSendid(String sendid) {
        this.sendid = sendid;
    }

    public Date getReptTime() {
        return this.reptTime;
    }
    
    public void setReptTime(Date reptTime) {
        this.reptTime = reptTime;
    }

    public String getCreateSubTime() {
        return this.createSubTime;
    }
    
    public void setCreateSubTime(String createSubTime) {
        this.createSubTime = createSubTime;
    }

    public Long getContentType() {
        return this.contentType;
    }
    
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    public Long getGwkind() {
        return this.gwkind;
    }
    
    public void setGwkind(Long gwkind) {
        this.gwkind = gwkind;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    public String getHwyid() {
        return this.hwyid;
    }
    
    public void setHwyid(String hwyid) {
        this.hwyid = hwyid;
    }

    public Long getMessagetype() {
        return this.messagetype;
    }
    
    public void setMessagetype(Long messagetype) {
        this.messagetype = messagetype;
    }
   








}