package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTAreaLocrecord generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTAreaLocrecord implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private Float longitude;

	private Float latitude;

	private String jmx;

	private String jmy;

	private Float speed;

	private Float direction;

	private Float height;

	private Float distance;

	private Long statlliteNum;

	private Date alarmTime;

	private String alarmType;

	private Date inputdate;

	private Long caseId;

	private String calledNumber;
	
	private String entCode;
	
	private String areaPoints;
	private String startTime;
	private String endTime;
	private String areaType;
	private Long speedLimit;
	private String locDesc;

	// Constructors

	public String getLocDesc() {
		return locDesc;
	}

	public void setLocDesc(String locDesc) {
		this.locDesc = locDesc;
	}

	public String getCalledNumber() {
		return calledNumber;
	}

	public void setCalledNumber(String calledNumber) {
		this.calledNumber = calledNumber;
	}

	/** default constructor */
	public AbstractTAreaLocrecord() {
	}

	/** full constructor */
	public AbstractTAreaLocrecord(String deviceId, Float longitude,
			Float latitude, String jmx, String jmy, Float speed,
			Float direction, Float height, Float distance, Long statlliteNum,
			Date alarmTime, String alarmType, Date inputdate, Long caseId,
			String calledNumber,String entCode) {
		this.deviceId = deviceId;
		this.longitude = longitude;
		this.latitude = latitude;
		this.jmx = jmx;
		this.jmy = jmy;
		this.speed = speed;
		this.direction = direction;
		this.height = height;
		this.distance = distance;
		this.statlliteNum = statlliteNum;
		this.alarmTime = alarmTime;
		this.alarmType = alarmType;
		this.inputdate = inputdate;
		this.caseId = caseId;
		this.calledNumber = calledNumber;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public String getJmx() {
		return this.jmx;
	}

	public void setJmx(String jmx) {
		this.jmx = jmx;
	}

	public String getJmy() {
		return this.jmy;
	}

	public void setJmy(String jmy) {
		this.jmy = jmy;
	}

	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}

	public Float getDirection() {
		return this.direction;
	}

	public void setDirection(Float direction) {
		this.direction = direction;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	public Long getStatlliteNum() {
		return this.statlliteNum;
	}

	public void setStatlliteNum(Long statlliteNum) {
		this.statlliteNum = statlliteNum;
	}

	public Date getAlarmTime() {
		return this.alarmTime;
	}

	public void setAlarmTime(Date alarmTime) {
		this.alarmTime = alarmTime;
	}

	public String getAlarmType() {
		return this.alarmType;
	}

	public void setAlarmType(String alarmType) {
		this.alarmType = alarmType;
	}

	public Date getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(Date inputdate) {
		this.inputdate = inputdate;
	}

	public Long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(Long caseId) {
		this.caseId = caseId;
	}

	public String getEntCode() {
		return entCode;
	}

	public void setEntCode(String entCode) {
		this.entCode = entCode;
	}

	public String getAreaPoints() {
		return areaPoints;
	}

	public void setAreaPoints(String areaPoints) {
		this.areaPoints = areaPoints;
	}

	public String getStartTime() {
		return startTime;
	}

	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}

	public String getEndTime() {
		return endTime;
	}

	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	public String getAreaType() {
		return areaType;
	}

	public void setAreaType(String areaType) {
		this.areaType = areaType;
	}

	public Long getSpeedLimit() {
		return speedLimit;
	}

	public void setSpeedLimit(Long speedLimit) {
		this.speedLimit = speedLimit;
	}

}