package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractShandongUnusedReportId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractShandongUnusedReportId  implements java.io.Serializable {


    // Fields    

     private String srcmobile;
     private String longid;
     private Long contentType;
     private String content;
     private String sendid;
     private Long rcode;
     private Date createTime;


    // Constructors

    /** default constructor */
    public AbstractShandongUnusedReportId() {
    }

    
    /** full constructor */
    public AbstractShandongUnusedReportId(String srcmobile, String longid, Long contentType, String content, String sendid, Long rcode, Date createTime) {
        this.srcmobile = srcmobile;
        this.longid = longid;
        this.contentType = contentType;
        this.content = content;
        this.sendid = sendid;
        this.rcode = rcode;
        this.createTime = createTime;
    }

   
    // Property accessors

    public String getSrcmobile() {
        return this.srcmobile;
    }
    
    public void setSrcmobile(String srcmobile) {
        this.srcmobile = srcmobile;
    }

    public String getLongid() {
        return this.longid;
    }
    
    public void setLongid(String longid) {
        this.longid = longid;
    }

    public Long getContentType() {
        return this.contentType;
    }
    
    public void setContentType(Long contentType) {
        this.contentType = contentType;
    }

    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }

    public String getSendid() {
        return this.sendid;
    }
    
    public void setSendid(String sendid) {
        this.sendid = sendid;
    }

    public Long getRcode() {
        return this.rcode;
    }
    
    public void setRcode(Long rcode) {
        this.rcode = rcode;
    }

    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractShandongUnusedReportId) ) return false;
		 AbstractShandongUnusedReportId castOther = ( AbstractShandongUnusedReportId ) other; 
         
		 return ( (this.getSrcmobile()==castOther.getSrcmobile()) || ( this.getSrcmobile()!=null && castOther.getSrcmobile()!=null && this.getSrcmobile().equals(castOther.getSrcmobile()) ) )
 && ( (this.getLongid()==castOther.getLongid()) || ( this.getLongid()!=null && castOther.getLongid()!=null && this.getLongid().equals(castOther.getLongid()) ) )
 && ( (this.getContentType()==castOther.getContentType()) || ( this.getContentType()!=null && castOther.getContentType()!=null && this.getContentType().equals(castOther.getContentType()) ) )
 && ( (this.getContent()==castOther.getContent()) || ( this.getContent()!=null && castOther.getContent()!=null && this.getContent().equals(castOther.getContent()) ) )
 && ( (this.getSendid()==castOther.getSendid()) || ( this.getSendid()!=null && castOther.getSendid()!=null && this.getSendid().equals(castOther.getSendid()) ) )
 && ( (this.getRcode()==castOther.getRcode()) || ( this.getRcode()!=null && castOther.getRcode()!=null && this.getRcode().equals(castOther.getRcode()) ) )
 && ( (this.getCreateTime()==castOther.getCreateTime()) || ( this.getCreateTime()!=null && castOther.getCreateTime()!=null && this.getCreateTime().equals(castOther.getCreateTime()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSrcmobile() == null ? 0 : this.getSrcmobile().hashCode() );
         result = 37 * result + ( getLongid() == null ? 0 : this.getLongid().hashCode() );
         result = 37 * result + ( getContentType() == null ? 0 : this.getContentType().hashCode() );
         result = 37 * result + ( getContent() == null ? 0 : this.getContent().hashCode() );
         result = 37 * result + ( getSendid() == null ? 0 : this.getSendid().hashCode() );
         result = 37 * result + ( getRcode() == null ? 0 : this.getRcode().hashCode() );
         result = 37 * result + ( getCreateTime() == null ? 0 : this.getCreateTime().hashCode() );
         return result;
   }   





}