package com.sosgps.wzt.orm;



/**
 * AbstractRefTermGroup generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractRefTermGroup  implements java.io.Serializable {


    // Fields    

     private RefTermGroupId id;
     private TTermGroup TTermGroup;
     private TTerminal TTerminal;


    // Constructors

    /** default constructor */
    public AbstractRefTermGroup() {
    }

	/** minimal constructor */
    public AbstractRefTermGroup(TTermGroup TTermGroup) {
        this.TTermGroup = TTermGroup;
    }
    
    /** full constructor */
    public AbstractRefTermGroup(TTermGroup TTermGroup, TTerminal TTerminal) {
        this.TTermGroup = TTermGroup;
        this.TTerminal = TTerminal;
    }

   
    // Property accessors

    public RefTermGroupId getId() {
        return this.id;
    }
    
    public void setId(RefTermGroupId id) {
        this.id = id;
    }

    public TTermGroup getTTermGroup() {
        return this.TTermGroup;
    }
    
    public void setTTermGroup(TTermGroup TTermGroup) {
        this.TTermGroup = TTermGroup;
    }

    public TTerminal getTTerminal() {
        return this.TTerminal;
    }
    
    public void setTTerminal(TTerminal TTerminal) {
        this.TTerminal = TTerminal;
    }
   








}