package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTHiwaytrafficinfo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTHiwaytrafficinfo  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String sp;
     private String contents;
     private String status;
     private String hiwayname;
     private Float longitude;
     private Float latitude;
     private String driction;
     private String ptype;
     private String gate;
     private Long mileage;
     private Long startpoint;
     private Long endpoint;
     private String flag;
     private Date receivetime;
     private Date modifytime;
     private String location;


    // Constructors

    /** default constructor */
    public AbstractTHiwaytrafficinfo() {
    }

    
    /** full constructor */
    public AbstractTHiwaytrafficinfo(String sp, String contents, String status, String hiwayname, Float longitude, Float latitude, String driction, String ptype, String gate, Long mileage, Long startpoint, Long endpoint, String flag, Date receivetime, Date modifytime, String location) {
        this.sp = sp;
        this.contents = contents;
        this.status = status;
        this.hiwayname = hiwayname;
        this.longitude = longitude;
        this.latitude = latitude;
        this.driction = driction;
        this.ptype = ptype;
        this.gate = gate;
        this.mileage = mileage;
        this.startpoint = startpoint;
        this.endpoint = endpoint;
        this.flag = flag;
        this.receivetime = receivetime;
        this.modifytime = modifytime;
        this.location = location;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getSp() {
        return this.sp;
    }
    
    public void setSp(String sp) {
        this.sp = sp;
    }

    public String getContents() {
        return this.contents;
    }
    
    public void setContents(String contents) {
        this.contents = contents;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public String getHiwayname() {
        return this.hiwayname;
    }
    
    public void setHiwayname(String hiwayname) {
        this.hiwayname = hiwayname;
    }

    public Float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    public Float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    public String getDriction() {
        return this.driction;
    }
    
    public void setDriction(String driction) {
        this.driction = driction;
    }

    public String getPtype() {
        return this.ptype;
    }
    
    public void setPtype(String ptype) {
        this.ptype = ptype;
    }

    public String getGate() {
        return this.gate;
    }
    
    public void setGate(String gate) {
        this.gate = gate;
    }

    public Long getMileage() {
        return this.mileage;
    }
    
    public void setMileage(Long mileage) {
        this.mileage = mileage;
    }

    public Long getStartpoint() {
        return this.startpoint;
    }
    
    public void setStartpoint(Long startpoint) {
        this.startpoint = startpoint;
    }

    public Long getEndpoint() {
        return this.endpoint;
    }
    
    public void setEndpoint(Long endpoint) {
        this.endpoint = endpoint;
    }

    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    public Date getReceivetime() {
        return this.receivetime;
    }
    
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    public Date getModifytime() {
        return this.modifytime;
    }
    
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
   








}