package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTDistanceDay generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTDistanceDay implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceId;

	private Float distance;

	private Date tjdate;

	// Constructors

	/** default constructor */
	public AbstractTDistanceDay() {
	}

	/** full constructor */
	public AbstractTDistanceDay(String deviceId, Float distance, Date tjdate) {
		this.deviceId = deviceId;
		this.distance = distance;
		this.tjdate = tjdate;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	public Date getTjdate() {
		return this.tjdate;
	}

	public void setTjdate(Date tjdate) {
		this.tjdate = tjdate;
	}

}