package com.sosgps.wzt.orm;

/**
 * AbstractTJbWfdm generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTJbWfdm implements java.io.Serializable {

	// Fields

	private Long wfxw;

	private String wfnr;

	// Constructors

	/** default constructor */
	public AbstractTJbWfdm() {
	}

	/** full constructor */
	public AbstractTJbWfdm(String wfnr) {
		this.wfnr = wfnr;
	}

	// Property accessors

	public Long getWfxw() {
		return this.wfxw;
	}

	public void setWfxw(Long wfxw) {
		this.wfxw = wfxw;
	}

	public String getWfnr() {
		return this.wfnr;
	}

	public void setWfnr(String wfnr) {
		this.wfnr = wfnr;
	}

}