package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTLineAlarm generated by MyEclipse Persistence Tools
 */

public abstract class AbstractTLineAlarm implements java.io.Serializable {

	// Fields

	private Long id;

	private String deviceid;

	private String entcode;

	private Long radio;

	private String xys;

	private Date crtdate;
	
	private String createman;
	
	private String flag;
	// Constructors

	/** default constructor */
	public AbstractTLineAlarm() {
	}

	/** full constructor */
	public AbstractTLineAlarm(String deviceid, String entcode, Long radio,
			String xys, Date crtdate, String createman, String flag) {
		this.deviceid = deviceid;
		this.entcode = entcode;
		this.radio = radio;
		this.xys = xys;
		this.crtdate = crtdate;
		this.createman = createman;
		this.flag = flag;
	}


	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceid() {
		return this.deviceid;
	}

	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid;
	}

	public String getEntcode() {
		return this.entcode;
	}

	public void setEntcode(String entcode) {
		this.entcode = entcode;
	}

	public Long getRadio() {
		return this.radio;
	}

	public void setRadio(Long radio) {
		this.radio = radio;
	}

	public String getXys() {
		return this.xys;
	}

	public void setXys(String xys) {
		this.xys = xys;
	}

	public Date getCrtdate() {
		return this.crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public String getCreateman() {
		return createman;
	}

	public void setCreateman(String createman) {
		this.createman = createman;
	}
	
	public String getFlag() {
		return this.flag;
	}

	public void setFlag(String flag) {
		this.flag = flag;
	}

}