package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTEnt generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSmsAccounts implements java.io.Serializable {

	private Integer id;
	private String entCode;
	private Integer smsAvailable;
	private Integer sms_sent_count;
	private Integer sms_total;
	private Date createDate;
	private TEnt tEnt;

	private static final long serialVersionUID = 1L;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEntCode() {
		return entCode;
	}

	public void setEntCode(String entCode) {
		this.entCode = entCode;
	}

	public Integer getSmsAvailable() {
		return smsAvailable;
	}

	public void setSmsAvailable(Integer smsAvailable) {
		this.smsAvailable = smsAvailable;
	}

	public Integer getSms_sent_count() {
		return sms_sent_count;
	}

	public void setSms_sent_count(Integer sms_sent_count) {
		this.sms_sent_count = sms_sent_count;
	}

	public Integer getSms_total() {
		return sms_total;
	}

	public void setSms_total(Integer sms_total) {
		this.sms_total = sms_total;
	}

	/** default constructor */
	public AbstractSmsAccounts() {
	}

	public Date getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public TEnt gettEnt() {
		return tEnt;
	}

	public void settEnt(TEnt tEnt) {
		this.tEnt = tEnt;
	}

	/** minimal constructor */
	public AbstractSmsAccounts(String entCode, Integer smsAvailable,
			Integer sms_sent_count, Integer sms_total) {
		this.entCode = entCode;
		this.smsAvailable = smsAvailable;
		this.sms_sent_count = sms_sent_count;
		this.sms_total = sms_total;
	}

}