package com.sosgps.wzt.orm;

import java.util.Date;

/**
 * AbstractTLocrecord generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTLocrecord implements java.io.Serializable {

	// Fields

	/**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Long id;
	private String deviceId;
	private Float latitude;
	private Float longitude;
	private String jmx;
	private String jmy;
	private Float speed;
	private Float direction;
	private Float height;
	private Float distance;
	private Long statlliteNum;
	private Date gpstime;
	private Date inputdate;
	private String locDesc;
	private Long signalFlag;
	
	private Long poiId;
	private String poiName;
	private String locateType;
	
	private String accStatus;
	private Float temperature;
	private String varExt1;
	private String imsi;
    private Float humidity;

	// Constructors

    public Float getHumidity() {
      return humidity;
    }
  
    public void setHumidity(Float humidity) {
      this.humidity = humidity;
    }

	public String getImsi() {
		return imsi;
	}

  public void setImsi(String imsi) {
		this.imsi = imsi;
	}

	public String getVarExt1() {
		return varExt1;
	}

	public void setVarExt1(String varExt1) {
		this.varExt1 = varExt1;
	}

	/** default constructor */
	public AbstractTLocrecord() {
	}

	/** full constructor */
	public AbstractTLocrecord(String deviceId, Float latitude, Float longitude,
			String jmx, String jmy, Float speed, Float direction, Float height,
			Float distance, Long statlliteNum, Date gpstime, Date inputdate,
			String locDesc,String varExt1, String imsi, Float temperature, Float humidity) {
		this.deviceId = deviceId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.jmx = jmx;
		this.jmy = jmy;
		this.speed = speed;
		this.direction = direction;
		this.height = height;
		this.distance = distance;
		this.statlliteNum = statlliteNum;
		this.gpstime = gpstime;
		this.inputdate = inputdate;
		this.locDesc = locDesc;
		this.varExt1 = varExt1;
		this.imsi = imsi;
        this.temperature = temperature;
        this.humidity = humidity;
	}

	// Property accessors

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	public Float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	public String getJmx() {
		return this.jmx;
	}

	public void setJmx(String jmx) {
		this.jmx = jmx;
	}

	public String getJmy() {
		return this.jmy;
	}

	public void setJmy(String jmy) {
		this.jmy = jmy;
	}

	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}

	public Float getDirection() {
		return this.direction;
	}

	public void setDirection(Float direction) {
		this.direction = direction;
	}

	public Float getHeight() {
		return this.height;
	}

	public void setHeight(Float height) {
		this.height = height;
	}

	public Float getDistance() {
		return this.distance;
	}

	public void setDistance(Float distance) {
		this.distance = distance;
	}

	public Long getStatlliteNum() {
		return this.statlliteNum;
	}

	public void setStatlliteNum(Long statlliteNum) {
		this.statlliteNum = statlliteNum;
	}

	public Date getGpstime() {
		return this.gpstime;
	}

	public void setGpstime(Date gpstime) {
		this.gpstime = gpstime;
	}

	public Date getInputdate() {
		return this.inputdate;
	}

	public void setInputdate(Date inputdate) {
		this.inputdate = inputdate;
	}

	public Long getSignalFlag() {
		return signalFlag;
	}

	public void setSignalFlag(Long signalFlag) {
		this.signalFlag = signalFlag;
	}

	public String getLocDesc() {
		return locDesc;
	}

	public void setLocDesc(String locDesc) {
		this.locDesc = locDesc;
	}

	public Long getPoiId() {
		return poiId;
	}

	public void setPoiId(Long poiId) {
		this.poiId = poiId;
	}

	public String getPoiName() {
		return poiName;
	}

	public void setPoiName(String poiName) {
		this.poiName = poiName;
	}

	public String getLocateType() {
		return locateType;
	}

	public void setLocateType(String locateType) {
		this.locateType = locateType;
	}

	public String getAccStatus() {
		return accStatus;
	}

	public void setAccStatus(String accStatus) {
		this.accStatus = accStatus;
	}

	public Float getTemperature() {
		return temperature;
	}

	public void setTemperature(Float temperature) {
		this.temperature = temperature;
	}

}