package com.sosgps.wzt.orm;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTVirtualGroup generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTVirtualGroup  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String groupName;
     private String entCode;
     private Date crtdate;
     private Set refTermVirgroups = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTVirtualGroup() {
    }

	/** minimal constructor */
    public AbstractTVirtualGroup(String groupName, String entCode) {
        this.groupName = groupName;
        this.entCode = entCode;
    }
    
    /** full constructor */
    public AbstractTVirtualGroup(String groupName, String entCode, Date crtdate, Set refTermVirgroups) {
        this.groupName = groupName;
        this.entCode = entCode;
        this.crtdate = crtdate;
        this.refTermVirgroups = refTermVirgroups;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getEntCode() {
        return this.entCode;
    }
    
    public void setEntCode(String entCode) {
        this.entCode = entCode;
    }

    public Date getCrtdate() {
        return this.crtdate;
    }
    
    public void setCrtdate(Date crtdate) {
        this.crtdate = crtdate;
    }

    public Set getRefTermVirgroups() {
        return this.refTermVirgroups;
    }
    
    public void setRefTermVirgroups(Set refTermVirgroups) {
        this.refTermVirgroups = refTermVirgroups;
    }
   








}