package com.sosgps.wzt.orm;

import java.util.Date;


/**
 * AbstractTTask generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTTask  implements java.io.Serializable {


    // Fields    

     private Long taskId;
     private String entCode;
     private String taskName;
     private Long taskType;
     private String taskDesc;
     private String taskPoints;
     private Date createDate;
     private Date modifyDate;
     private String createPerson;


    // Constructors

    /** default constructor */
    public AbstractTTask() {
    }

	/** minimal constructor */
    public AbstractTTask(String entCode, String taskName) {
        this.entCode = entCode;
        this.taskName = taskName;
    }
    
    /** full constructor */
    public AbstractTTask(String entCode, String taskName, Long taskType, String taskDesc, String taskPoints, Date createDate, Date modifyDate, String createPerson) {
        this.entCode = entCode;
        this.taskName = taskName;
        this.taskType = taskType;
        this.taskDesc = taskDesc;
        this.taskPoints = taskPoints;
        this.createDate = createDate;
        this.modifyDate = modifyDate;
        this.createPerson = createPerson;
    }

   
    // Property accessors

    public Long getTaskId() {
        return this.taskId;
    }
    
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    public String getEntCode() {
        return this.entCode;
    }
    
    public void setEntCode(String entCode) {
        this.entCode = entCode;
    }

    public String getTaskName() {
        return this.taskName;
    }
    
    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public Long getTaskType() {
        return this.taskType;
    }
    
    public void setTaskType(Long taskType) {
        this.taskType = taskType;
    }

    public String getTaskDesc() {
        return this.taskDesc;
    }
    
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc;
    }

    public String getTaskPoints() {
        return this.taskPoints;
    }
    
    public void setTaskPoints(String taskPoints) {
        this.taskPoints = taskPoints;
    }

    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Date getModifyDate() {
        return this.modifyDate;
    }
    
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    public String getCreatePerson() {
        return this.createPerson;
    }
    
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }
   








}