package com.sosgps.wzt.orm;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractTModuleGroup generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTModuleGroup  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String groupName;
     private Long groupLevel;
     private String groupDesc;
     private Long parentId;
     private String createBy;
     private String createDate;
     private String usageFlag;
     private Set TModules = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractTModuleGroup() {
    }

	/** minimal constructor */
    public AbstractTModuleGroup(String groupName, Long groupLevel, String createBy, String createDate, String usageFlag) {
        this.groupName = groupName;
        this.groupLevel = groupLevel;
        this.createBy = createBy;
        this.createDate = createDate;
        this.usageFlag = usageFlag;
    }
    
    /** full constructor */
    public AbstractTModuleGroup(String groupName, Long groupLevel, String groupDesc, Long parentId, String createBy, String createDate, String usageFlag, Set TModules) {
        this.groupName = groupName;
        this.groupLevel = groupLevel;
        this.groupDesc = groupDesc;
        this.parentId = parentId;
        this.createBy = createBy;
        this.createDate = createDate;
        this.usageFlag = usageFlag;
        this.TModules = TModules;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public Long getGroupLevel() {
        return this.groupLevel;
    }
    
    public void setGroupLevel(Long groupLevel) {
        this.groupLevel = groupLevel;
    }

    public String getGroupDesc() {
        return this.groupDesc;
    }
    
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc;
    }

    public Long getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    public String getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getUsageFlag() {
        return this.usageFlag;
    }
    
    public void setUsageFlag(String usageFlag) {
        this.usageFlag = usageFlag;
    }

    public Set getTModules() {
        return this.TModules;
    }
    
    public void setTModules(Set TModules) {
        this.TModules = TModules;
    }
   








}