package com.sosgps.wzt.orm;



/**
 * AbstractTVersion generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTVersion  implements java.io.Serializable {


    // Fields    

     private Long id;
     private Long version;
     private String typeCode;
     private String typeDesc;
     private String versionDesc;


    // Constructors

    /** default constructor */
    public AbstractTVersion() {
    }

    
    /** full constructor */
    public AbstractTVersion(Long version, String typeCode, String typeDesc, String versionDesc) {
        this.version = version;
        this.typeCode = typeCode;
        this.typeDesc = typeDesc;
        this.versionDesc = versionDesc;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return this.version;
    }
    
    public void setVersion(Long version) {
        this.version = version;
    }

    public String getTypeCode() {
        return this.typeCode;
    }
    
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public String getTypeDesc() {
        return this.typeDesc;
    }
    
    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    public String getVersionDesc() {
        return this.versionDesc;
    }
    
    public void setVersionDesc(String versionDesc) {
        this.versionDesc = versionDesc;
    }
   








}