package com.sosgps.wzt.orm;

import java.util.Date;

// Generated by MyEclipse Persistence Tools

/**
 * CarTypeInfo generated by MyEclipse Persistence Tools
 */
@SuppressWarnings("serial")
public class CarTypeInfo extends AbstractCarTypeInfo implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public CarTypeInfo() {
	}

	/** full constructor */
	public CarTypeInfo(String typeName, String iconPath, String desction,
			String enCode, Long oilWear, Long userId, Long changeUserId, 
			Date crtdate, Date changeDate) {
		super(typeName, iconPath, desction, enCode, oilWear, userId, changeUserId, 
				crtdate, changeDate);
	}

}
