package com.sosgps.wzt.orm;

// Generated 2010-4-10 16:44:48 by Hibernate Tools 3.2.5.Beta

/**
 * RefLayerPoi generated by hbm2java
 */
public class RefLayerPoi implements java.io.Serializable {

	private Long id;
	private TPoi TPoi;
	private TLayers TLayers;

	public RefLayerPoi() {
	}

	public RefLayerPoi(TPoi TPoi, TLayers TLayers) {
		this.TPoi = TPoi;
		this.TLayers = TLayers;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TPoi getTPoi() {
		return this.TPoi;
	}

	public void setTPoi(TPoi TPoi) {
		this.TPoi = TPoi;
	}

	public TLayers getTLayers() {
		return this.TLayers;
	}

	public void setTLayers(TLayers TLayers) {
		this.TLayers = TLayers;
	}

}
