package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefTermGroupId generated by MyEclipse - Hibernate Tools
 */
public class RefTermGroupId extends AbstractRefTermGroupId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefTermGroupId() {
    }

	/** minimal constructor */
    public RefTermGroupId(TTermGroup TTermGroup) {
        super(TTermGroup);        
    }
    
    /** full constructor */
    public RefTermGroupId(TTerminal TTerminal, TTermGroup TTermGroup) {
        super(TTerminal, TTermGroup);        
    }
   
}
