package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefTermVirgroup generated by MyEclipse - Hibernate Tools
 */
public class RefTermVirgroup extends AbstractRefTermVirgroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefTermVirgroup() {
    }

    
    /** full constructor */
    public RefTermVirgroup(TVirtualGroup TVirtualGroup, TTerminal TTerminal) {
        super(TVirtualGroup, TTerminal);        
    }
   
}
