package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefTermGroup generated by MyEclipse - Hibernate Tools
 */
public class RefTermGroup extends AbstractRefTermGroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefTermGroup() {
    }

	/** minimal constructor */
    public RefTermGroup(TTermGroup TTermGroup) {
        super(TTermGroup);        
    }
    
    /** full constructor */
    public RefTermGroup(TTermGroup TTermGroup, TTerminal TTerminal) {
        super(TTermGroup, TTerminal);        
    }
   
}
