package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefUserRole generated by MyEclipse - Hibernate Tools
 */
public class RefUserRole extends AbstractRefUserRole implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefUserRole() {
    }

    
    /** full constructor */
    public RefUserRole(TRole TRole, TUser TUser) {
        super(TRole, TUser);        
    }
   
}
