package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefUserTgroup generated by MyEclipse - Hibernate Tools
 */
public class RefUserTgroup extends AbstractRefUserTgroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefUserTgroup() {
    }

    
    /** full constructor */
    public RefUserTgroup(TTermGroup TTermGroup) {
        super(TTermGroup);        
    }
   
}
