package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * RefUserTgroupId generated by MyEclipse - Hibernate Tools
 */
public class RefUserTgroupId extends AbstractRefUserTgroupId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public RefUserTgroupId() {
    }

	/** minimal constructor */
    public RefUserTgroupId(Long userId) {
        super(userId);        
    }
    
    /** full constructor */
    public RefUserTgroupId(Long userId, TTermGroup TTermGroup) {
        super(userId, TTermGroup);        
    }
   
}
