package com.sosgps.wzt.orm;

// Generated 2010-4-10 16:44:48 by Hibernate Tools 3.2.5.Beta

/**
 * RefUserLayer generated by hbm2java
 */
public class RefUserLayer implements java.io.Serializable {

	private Long id;
	private TLayers TLayers;
	private Long userId;
	private String visible;

	public RefUserLayer() {
	}

	public RefUserLayer(TLayers TLayers, Long userId, String visible) {
		this.TLayers = TLayers;
		this.userId = userId;
		this.visible = visible;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public TLayers getTLayers() {
		return this.TLayers;
	}

	public void setTLayers(TLayers TLayers) {
		this.TLayers = TLayers;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getVisible() {
		return this.visible;
	}

	public void setVisible(String visible) {
		this.visible = visible;
	}

}
