package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * ShandongSmsWait generated by MyEclipse - Hibernate Tools
 */
public class ShandongSmsWait extends AbstractShandongSmsWait implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ShandongSmsWait() {
    }

	/** minimal constructor */
    public ShandongSmsWait(Date createTime, Date sendTime, Date validTime, String desmobile, String content, Long contentType, Long retry, Long gwkind, Long report) {
        super(createTime, sendTime, validTime, desmobile, content, contentType, retry, gwkind, report);        
    }
    
    /** full constructor */
    public ShandongSmsWait(Date createTime, Date sendTime, Date validTime, String longid, String desmobile, String content, Long contentType, Long retry, Long gwkind, Long report, String hwyid, Long messagetype) {
        super(createTime, sendTime, validTime, longid, desmobile, content, contentType, retry, gwkind, report, hwyid, messagetype);        
    }
   
}
