package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * ShandongSmsRecv generated by MyEclipse - Hibernate Tools
 */
public class ShandongSmsRecv extends AbstractShandongSmsRecv implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ShandongSmsRecv() {
    }

	/** minimal constructor */
    public ShandongSmsRecv(Date createTime, Date validTime, String srcmobile, Long contentType) {
        super(createTime, validTime, srcmobile, contentType);        
    }
    
    /** full constructor */
    public ShandongSmsRecv(Date createTime, Date validTime, String srcmobile, String longid, Long contentType, String content) {
        super(createTime, validTime, srcmobile, longid, contentType, content);        
    }
   
}
