package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * ShandongUnusedReport generated by MyEclipse - Hibernate Tools
 */
public class ShandongUnusedReport extends AbstractShandongUnusedReport implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ShandongUnusedReport() {
    }

    
   
}
