package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * ShandongUnusedReportId generated by MyEclipse - Hibernate Tools
 */
public class ShandongUnusedReportId extends AbstractShandongUnusedReportId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ShandongUnusedReportId() {
    }

    
    /** full constructor */
    public ShandongUnusedReportId(String srcmobile, String longid, Long contentType, String content, String sendid, Long rcode, Date createTime) {
        super(srcmobile, longid, contentType, content, sendid, rcode, createTime);        
    }
   
}
