package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * ShandongLogRecv generated by MyEclipse - Hibernate Tools
 */
public class ShandongLogRecv extends AbstractShandongLogRecv implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ShandongLogRecv() {
    }

	/** minimal constructor */
    public ShandongLogRecv(Date createTime, String srcmobile, Long contentType, String createSubTime) {
        super(createTime, srcmobile, contentType, createSubTime);        
    }
    
    /** full constructor */
    public ShandongLogRecv(Date createTime, String srcmobile, String longid, Long contentType, String content, String createSubTime) {
        super(createTime, srcmobile, longid, contentType, content, createSubTime);        
    }
   
}
