package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TAlarmTjMonth generated by MyEclipse - Hibernate Tools
 */
public class TAlarmTjMonth extends AbstractTAlarmTjMonth implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TAlarmTjMonth() {
    }

    
    /** full constructor */
    public TAlarmTjMonth(String deviceId, Long speedAlarm, Long inactiveAlarm, Long areaAlarm, Long lineAlarm, Date tjdate, Long emerAlarm, Long callRecord, Long shortmessRecord) {
        super(deviceId, speedAlarm, inactiveAlarm, areaAlarm, lineAlarm, tjdate, emerAlarm, callRecord, shortmessRecord);        
    }
   
}
