package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TAlarmShow generated by MyEclipse Persistence Tools
 */
public class TAlarmShow extends AbstractTAlarmShow implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TAlarmShow() {
	}
	/** full constructor */
	public TAlarmShow(String deviceId, String alarmType, String alarmContent,
			String flag, Date alarmDate, Date stopAlarmDate, Long alarmId) {
		super(deviceId, alarmType, alarmContent, flag, alarmDate,
				stopAlarmDate, alarmId);
	}

}
