package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TAreaLocrecord generated by MyEclipse Persistence Tools
 */
public class TAreaLocrecord extends AbstractTAreaLocrecord implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TAreaLocrecord() {
	}

	/** full constructor */
	public TAreaLocrecord(String deviceId, Float longitude, Float latitude,
			String jmx, String jmy, Float speed, Float direction, Float height,
			Float distance, Long statlliteNum, Date alarmTime,
			String alarmType, Date inputdate, Long caseId, String calledNumber,String entCode) {
		super(deviceId, longitude, latitude, jmx, jmy, speed, direction,
				height, distance, statlliteNum, alarmTime, alarmType,
				inputdate, caseId, calledNumber,entCode);
	}

}
