package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * TArea generated by MyEclipse - Hibernate Tools
 */
public class TArea extends AbstractTArea implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TArea() {
    }

    
    /** full constructor */
//    public TArea(String name, String xy, String beginDate, String endDate, String epCode, String deviceId, String type, Date createdate, String createman, String flag, String areaType, Long lineStyle, Long lineColor, Long lineWidth, Long lineAlpha, Long fillColor, Long fillStyle, Long fillAlpha, Long fillShow, Set refTermAreaalarms) {
//        super(name, xy, beginDate, endDate, epCode, deviceId, type, createdate, createman, flag, areaType, lineStyle, lineColor, lineWidth, lineAlpha, fillColor, fillStyle, fillAlpha, fillShow, refTermAreaalarms);        
//    }
    public TArea(String name, String xy, String epCode, String type, Date createdate, String createman, String flag, String areaType, Set refTermAreaalarms) {
        super(name, xy, epCode, createdate, createman, flag, areaType, refTermAreaalarms);        
    }
}
