package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TCallRecord generated by MyEclipse - Hibernate Tools
 */
public class TCallRecord extends AbstractTCallRecord implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TCallRecord() {
    }

    
    /** full constructor */
    public TCallRecord(String callerNumber, String calledNumber, Date calleDate, String deviceId, String callType, String content, String memo) {
        super(callerNumber, calledNumber, calleDate, deviceId, callType, content, memo);        
    }
   
}
