package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

/**
 * TCarspeedTjDay generated by MyEclipse Persistence Tools
 */
public class TCarspeedTjDay extends AbstractTCarspeedTjDay implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TCarspeedTjDay() {
	}

	/** minimal constructor */
	public TCarspeedTjDay(Long id) {
		super(id);
	}

	/** full constructor */
	public TCarspeedTjDay(Long id, String deviceId, Double low4T, Double low4R,
			Double high4low8T, Double high4low8R, Double high8low12T,
			Double high8low12R, Double high12low16T, Double high12low16R,
			Double high16T, Double high16R, Double maxspeed, String dateDay) {
		super(id, deviceId, low4T, low4R, high4low8T, high4low8R, high8low12T,
				high8low12R, high12low16T, high12low16R, high16T, high16R,
				maxspeed, dateDay);
	}

}
