package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TCitytrafficinfo generated by MyEclipse - Hibernate Tools
 */
public class TCitytrafficinfo extends AbstractTCitytrafficinfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TCitytrafficinfo() {
    }

    
    /** full constructor */
    public TCitytrafficinfo(String sp, String contents, String intersection, Long liftingtime, Float longitude, Float latitude, Date receivetime, String flag,String dirction,Date modifytiem) {
        super(sp, contents, intersection, liftingtime, longitude, latitude, receivetime, flag,dirction ,modifytiem);        
    }
   
}
