package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * TDictItem generated by MyEclipse - Hibernate Tools
 */
public class TDictItem extends AbstractTDictItem implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TDictItem() {
    }

	/** minimal constructor */
    public TDictItem(TDict TDict, String itemName, String itemCode, String dictCode) {
        super(TDict, itemName, itemCode, dictCode);        
    }
    
    /** full constructor */
    public TDictItem(TDict TDict, String itemName, String itemCode, String dictCode, String usageFlag) {
        super(TDict, itemName, itemCode, dictCode, usageFlag);        
    }
   
}
