package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TDistanceDay generated by MyEclipse Persistence Tools
 */
public class TDistanceDay extends AbstractTDistanceDay implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TDistanceDay() {
	}

	/** full constructor */
	public TDistanceDay(String deviceId, Float distance, Date tjdate) {
		super(deviceId, distance, tjdate);
	}

}
