package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TDistanceYear generated by MyEclipse Persistence Tools
 */
public class TDistanceYear extends AbstractTDistanceYear implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TDistanceYear() {
	}

	/** full constructor */
	public TDistanceYear(String deviceId, Float distance, Date tjdate) {
		super(deviceId, distance, tjdate);
	}

}
