package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TDistanceMonth generated by MyEclipse Persistence Tools
 */
public class TDistanceMonth extends AbstractTDistanceMonth implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TDistanceMonth() {
	}

	/** full constructor */
	public TDistanceMonth(String deviceId, Float distance, Date tjdate) {
		super(deviceId, distance, tjdate);
	}

}
