package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TFreq generated by MyEclipse Persistence Tools
 */
public class TFreq extends AbstractTFreq implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public TFreq() {
	}

	/** full constructor */
	public TFreq(String value, String deviceId, Date crtdate, String crtman) {
		super(value, deviceId, crtdate, crtman);
	}

}
