package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * THiwaytrafficinfo generated by MyEclipse - Hibernate Tools
 */
public class THiwaytrafficinfo extends AbstractTHiwaytrafficinfo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public THiwaytrafficinfo() {
    }

    
    /** full constructor */
    public THiwaytrafficinfo(String sp, String contents, String status, String hiwayname, Float longitude, Float latitude, String driction, String ptype, String gate, Long mileage, Long startpoint, Long endpoint, String flag, Date receivetime, Date modifytime, String location) {
        super(sp, contents, status, hiwayname, longitude, latitude, driction, ptype, gate, mileage, startpoint, endpoint, flag, receivetime, modifytime, location);        
    }
   
}
