package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TInactiveAlarmLoc generated by MyEclipse - Hibernate Tools
 */
public class TInactiveAlarmLoc extends AbstractTInactiveAlarmLoc implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TInactiveAlarmLoc() {
    }

    
    /** full constructor */
    public TInactiveAlarmLoc(TTerminal TTerminal, Long longitude, Long latitude, Long jmx, Long jmy, Long speed, Long direction, Long height, Long distance, Long statlliteNum, Date alarmTime, Date inputdate) {
        super(TTerminal, longitude, latitude, jmx, jmy, speed, direction, height, distance, statlliteNum, alarmTime, inputdate);        
    }
   
}
