package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

/**
 * TJbWfdm generated by MyEclipse Persistence Tools
 */
public class TJbWfdm extends AbstractTJbWfdm implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public TJbWfdm() {
	}

	/** full constructor */
	public TJbWfdm(String wfnr) {
		super(wfnr);
	}

}
