package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TLastLocrecord generated by MyEclipse Persistence Tools
 */
public class TLastLocrecord extends AbstractTLastLocrecord implements
		java.io.Serializable {

	// Constructors

	/**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
	public TLastLocrecord() {
	}

	/** full constructor */
	public TLastLocrecord(Float latitude, Float longitude, String jmx,
			String jmy, Float speed, Float direction, Float height,
			Float distance, Float statlliteNum, String deviceId, Date gpstime,
			Date inputdate, String locateType, Float temperature, Float humidity) {
		super(latitude, longitude, jmx, jmy, speed, direction, height,
				distance, statlliteNum, deviceId, gpstime, inputdate, locateType, temperature, humidity);
	}

}
