package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TLbsLocrecord generated by MyEclipse - Hibernate Tools
 */
public class TLbsLocrecord extends AbstractTLbsLocrecord implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TLbsLocrecord() {
    }

    
    /** full constructor */
    public TLbsLocrecord(String simcard, String x, String y, String entCode, Date lbstime, String errorCode, String errorDesc, String locDesc, String lngx, String laty, Long type) {
        super(simcard, x, y, entCode, lbstime, errorCode, errorDesc, locDesc, lngx, laty, type);        
    }
   
}
