package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TLianxuxingshiTj generated by MyEclipse Persistence Tools
 */
public class TLianxuxingshiTj extends AbstractTLianxuxingshiTj implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TLianxuxingshiTj() {
	}

	/** full constructor */
	public TLianxuxingshiTj(String deviceId, Date startTime, Date endTime,
			Long continueTime) {
		super(deviceId, startTime, endTime, continueTime);
	}

}
