package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TLineAlarm generated by MyEclipse Persistence Tools
 */
public class TLineAlarm extends AbstractTLineAlarm implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TLineAlarm() {
	}

	/** full constructor */
	/** full constructor */
	public TLineAlarm(String deviceid, String entcode, Long radio, String xys,
			Date crtdate, String createman, String flag) {
		super(deviceid, entcode, radio, xys, crtdate, createman, flag);
	}

}
