package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TMessage generated by MyEclipse - Hibernate Tools
 */
public class TMessage extends AbstractTMessage implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TMessage() {
    }

    
    /** full constructor */
    public TMessage(String sender, String receiver, String content, String msgType, Date createdate, String createman) {
        super(sender, receiver, content, msgType, createdate, createman);        
    }
   
}
