package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.List;
import java.util.Set;

import com.sosgps.wzt.system.util.CheckRightUtil;


/**
 * TModuleGroup generated by MyEclipse - Hibernate Tools
 */
public class TModuleGroup extends AbstractTModuleGroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TModuleGroup() {
    }
    public TModuleGroup(Long groupId,String groupName){ 
    	super();
    	this.setId(groupId);
    	this.setGroupName(groupName);
    }
	/** minimal constructor */
    public TModuleGroup(String groupName, Long groupLevel, String createBy, String createDate, String usageFlag) {
        super(groupName, groupLevel, createBy, createDate, usageFlag);        
    }
    
    /** full constructor */
    public TModuleGroup(String groupName, Long groupLevel, String groupDesc, Long parentId, String createBy, String createDate, String usageFlag, Set TModules) {
        super(groupName, groupLevel, groupDesc, parentId, createBy, createDate, usageFlag, TModules);        
    }
    public List getChildGroup(java.lang.Long parentId,java.lang.Long userId){
        List list = null;
        CheckRightUtil checkRightUtil = new CheckRightUtil();
        list = checkRightUtil.queryChildModuleGroup(parentId,userId);
        return list;
    }
    
    public List getModuleList(java.lang.Long groupId,java.lang.Long userId){
    		List list = null;
    	CheckRightUtil checkRightUtil = new CheckRightUtil();
        list = checkRightUtil.queryModuleList(groupId,userId);
        return list;
    }
   
}
