package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TMutiMedium generated by MyEclipse Persistence Tools
 */
public class TMutiMedium extends AbstractTMutiMedium implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TMutiMedium() {
	}

	/** full constructor */
	public TMutiMedium(String deviceId, String image, Float lantitude,
			Float longitude, String jmx, String jmy, Date uploadTime,
			String imgType) {
		super(deviceId, image, lantitude, longitude, jmx, jmy, uploadTime,
				imgType);
	}

}
