package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TStructions generated by MyEclipse - Hibernate Tools
 */
public class TStructions extends AbstractTStructions implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TStructions() {
    }

    
    /** full constructor */
    public TStructions(TTerminal TTerminal, String instruction, String state, String type, String param, String reply, Date createdate, String createman) {
        super(TTerminal, instruction, state, type, param, reply, createdate, createman);        
    }
   
}
