package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * TTask generated by MyEclipse - Hibernate Tools
 */
public class TTask extends AbstractTTask implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TTask() {
    }

	/** minimal constructor */
    public TTask(String entCode, String taskName) {
        super(entCode, taskName);        
    }
    
    /** full constructor */
    public TTask(String entCode, String taskName, Long taskType, String taskDesc, String taskPoints, Date createDate, Date modifyDate, String createPerson) {
        super(entCode, taskName, taskType, taskDesc, taskPoints, createDate, modifyDate, createPerson);        
    }
   
}
