package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * TTerminal generated by MyEclipse - Hibernate Tools
 */
public class TTerminal extends AbstractTTerminal implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TTerminal() {
    }

	/** minimal constructor */
    public TTerminal(String termName) {
        super(termName);        
    }
    
    /** full constructor */
    public TTerminal(TEntTermtype TEntTermtype, String termName, String imgUrl, Long suiteId, String entCode, String simcard, String oemCode,
			String driverNumber, String locateType, Long carTypeId,String isAllocate, String subCompany, Set TLocrecords, Set TMutiMediums, Set TLastLocrecords, Set TInactiveAlarmLocs, Set refTermGroups, Set TStructionses, Set TSpeedAlarmLocs, Set TAreaLocrecords, Set refTermAttrules, Set refTermSimrules, Set refTermVirgroups, Set refTermAreaalarms, String imsi) {
        super(TEntTermtype, termName, imgUrl, suiteId, entCode, simcard,oemCode,driverNumber, locateType,carTypeId,isAllocate,subCompany,TLocrecords, TMutiMediums, TLastLocrecords, TInactiveAlarmLocs, refTermGroups, TStructionses, TSpeedAlarmLocs, TAreaLocrecords, refTermAttrules, refTermSimrules, refTermVirgroups, refTermAreaalarms, imsi);        
    }
   
}
