package com.sosgps.wzt.orm;

// Generated 2009-12-16 10:15:48 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * TTermNotify generated by hbm2java
 */
public class TTermNotify implements java.io.Serializable {

	private Long id;
	private String deviceId;
	private String notifyNumber;
	private Long userId;
	private String userName;
	private Date createDate;
	private String entCode;

	public TTermNotify() {
	}

	public TTermNotify(String deviceId, String notifyNumber, Long userId,
			String userName, String entCode) {
		this.deviceId = deviceId;
		this.notifyNumber = notifyNumber;
		this.userId = userId;
		this.userName = userName;
		this.entCode = entCode;
	}

	public TTermNotify(String deviceId, String notifyNumber, Long userId,
			String userName, Date createDate, String entCode) {
		this.deviceId = deviceId;
		this.notifyNumber = notifyNumber;
		this.userId = userId;
		this.userName = userName;
		this.createDate = createDate;
		this.entCode = entCode;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public String getNotifyNumber() {
		return this.notifyNumber;
	}

	public void setNotifyNumber(String notifyNumber) {
		this.notifyNumber = notifyNumber;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getEntCode() {
		return this.entCode;
	}

	public void setEntCode(String entCode) {
		this.entCode = entCode;
	}

}
