package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * TTermGroup generated by MyEclipse - Hibernate Tools
 */
public class TTermGroup extends AbstractTTermGroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TTermGroup() {
    }

	/** minimal constructor */
    public TTermGroup(String groupName, Long parentId, Long groupSort) {
        super(groupName, parentId, groupSort);        
    }
    
    /** full constructor */
    public TTermGroup(TEnt TEnt, String groupName, Long parentId, Long groupSort, Set refUserTgroups, Set refTermGroups) {
        super(TEnt, groupName, parentId, groupSort, refUserTgroups, refTermGroups);        
    }
   
}
