package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools


/**
 * TDistanceDay generated by MyEclipse Persistence Tools
 */
public class TTotalDistance extends AbstractTTotalDistance implements
		java.io.Serializable {

	// Constructors

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/** default constructor */
	public TTotalDistance() {
	}

	/** full constructor */
	public TTotalDistance(String deviceId, Float distance, String empCode, Float userId) {
		super(deviceId, distance, empCode, userId);
	}

}
