package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * TUser generated by MyEclipse - Hibernate Tools
 */
public class TUser extends AbstractTUser implements java.io.Serializable {

    // Constructors
	 private TRole role;
    /** default constructor */
    public TUser() {
    }
    public void setRole(TRole _role){
    	this.role = _role;
    }
    public TRole getRole(){
        TRole role = null;
        if(this.getRefUserRoles()!=null &&this.getRefUserRoles().size() >0){
            Object[] userole = this.getRefUserRoles().toArray();
            RefUserRole refUserRole = (RefUserRole)userole[0];
            role = refUserRole.getTRole();
        }else{
        	role = this.role;
        }
        return role;
        
    }
	/** minimal constructor */
    public TUser(String userAccount, String userPassword, String createDate, String usageFlag) {
        super(userAccount, userPassword, createDate, usageFlag);        
    }
    
    /** full constructor */
    public TUser(String userAccount, String userPassword, String createBy, String createDate, String usageFlag, String empCode, Set refUserRoles) {
        super(userAccount, userPassword, createBy, createDate, usageFlag, empCode, refUserRoles);        
    }
   
}
