package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools



/**
 * TVersion generated by MyEclipse - Hibernate Tools
 */
public class TVersion extends AbstractTVersion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TVersion() {
    }

    
    /** full constructor */
    public TVersion(Long version, String typeCode, String typeDesc, String versionDesc) {
        super(version, typeCode, typeDesc, versionDesc);        
    }
   
}
