package com.sosgps.wzt.orm;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * TVirtualGroup generated by MyEclipse - Hibernate Tools
 */
public class TVirtualGroup extends AbstractTVirtualGroup implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public TVirtualGroup() {
    }

	/** minimal constructor */
    public TVirtualGroup(String groupName, String entCode) {
        super(groupName, entCode);        
    }
    
    /** full constructor */
    public TVirtualGroup(String groupName, String entCode, Date crtdate, Set refTermVirgroups) {
        super(groupName, entCode, crtdate, refTermVirgroups);        
    }
   
}
