package com.sosgps.wzt.orm;

// Generated 2010-4-24 20:08:51 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * TVisitCountTj generated by hbm2java
 */
@SuppressWarnings("serial")
public class TVisitCountTj implements java.io.Serializable {

	private Long id;
	private String deviceId;
	private String vehicleNumber;
	private Long visitCount;
	private Long visitCusCount;
	private Long visitPlaceCount;
	private Date crtdate;
	private Date tjDate;

	public TVisitCountTj() {
	}

	public TVisitCountTj(String deviceId) {
		this.deviceId = deviceId;
	}

	public TVisitCountTj(String deviceId, String vehicleNumber, 
			Long visitCount, Long visitCusCount, Long visitPlaceCount, 
			Date crtdate, Date tjDate) {
		this.deviceId = deviceId;
		this.vehicleNumber = vehicleNumber;
		this.visitCount = visitCount;
		this.visitCusCount = visitCusCount;
		this.visitPlaceCount = visitPlaceCount;
		this.crtdate = crtdate;
		this.tjDate = tjDate;
	}

	public String getVehicleNumber() {
		return vehicleNumber;
	}

	public void setVehicleNumber(String vehicleNumber) {
		this.vehicleNumber = vehicleNumber;
	}

	public Long getVisitCount() {
		return visitCount;
	}

	public void setVisitCount(Long visitCount) {
		this.visitCount = visitCount;
	}

	public Long getVisitCusCount() {
		return visitCusCount;
	}

	public void setVisitCusCount(Long visitCusCount) {
		this.visitCusCount = visitCusCount;
	}

	public Long getVisitPlaceCount() {
		return visitPlaceCount;
	}

	public void setVisitPlaceCount(Long visitPlaceCount) {
		this.visitPlaceCount = visitPlaceCount;
	}

	public Date getCrtdate() {
		return crtdate;
	}

	public void setCrtdate(Date crtdate) {
		this.crtdate = crtdate;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}


	public Date getTjDate() {
		return this.tjDate;
	}

	public void setTjDate(Date tjDate) {
		this.tjDate = tjDate;
	}

}
