package com.sosgps.wzt.orm;

// Generated 2010-4-24 20:08:51 by Hibernate Tools 3.2.5.Beta

import java.util.Date;

/**
 * TVisitTj generated by hbm2java
 */
public class TVisitTj implements java.io.Serializable {

	private Long id;
	private String deviceId;
	private Date arriveTime;
	private Date leaveTime;
	private Date tjDate;
	private Long poiId;
	private Long locId;
	private Double longitude;
	private Double latitude;
	private String jmx;
	private String jmy;
	private String locDesc;
	private String poiName;

	public TVisitTj() {
	}

	public TVisitTj(String deviceId) {
		this.deviceId = deviceId;
	}

	public TVisitTj(String deviceId, Date arriveTime, Date leaveTime,
			Date tjDate, Long poiId, Long locId, Double longitude,
			Double latitude, String jmx, String jmy, String locDesc) {
		this.deviceId = deviceId;
		this.arriveTime = arriveTime;
		this.leaveTime = leaveTime;
		this.tjDate = tjDate;
		this.poiId = poiId;
		this.locId = locId;
		this.longitude = longitude;
		this.latitude = latitude;
		this.jmx = jmx;
		this.jmy = jmy;
		this.locDesc = locDesc;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	public Date getArriveTime() {
		return this.arriveTime;
	}

	public void setArriveTime(Date arriveTime) {
		this.arriveTime = arriveTime;
	}

	public Date getLeaveTime() {
		return this.leaveTime;
	}

	public void setLeaveTime(Date leaveTime) {
		this.leaveTime = leaveTime;
	}

	public Date getTjDate() {
		return this.tjDate;
	}

	public void setTjDate(Date tjDate) {
		this.tjDate = tjDate;
	}

	public Long getPoiId() {
		return this.poiId;
	}

	public void setPoiId(Long poiId) {
		this.poiId = poiId;
	}

	public Long getLocId() {
		return this.locId;
	}

	public void setLocId(Long locId) {
		this.locId = locId;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public String getJmx() {
		return this.jmx;
	}

	public void setJmx(String jmx) {
		this.jmx = jmx;
	}

	public String getJmy() {
		return this.jmy;
	}

	public void setJmy(String jmy) {
		this.jmy = jmy;
	}

	public String getLocDesc() {
		return this.locDesc;
	}

	public void setLocDesc(String locDesc) {
		this.locDesc = locDesc;
	}

	public String getPoiName() {
		return poiName;
	}

	public void setPoiName(String poiName) {
		this.poiName = poiName;
	}

}
