package com.sosgps.wzt.orm;

// Generated by MyEclipse Persistence Tools

import java.util.Date;

/**
 * TYwClwfSdall generated by MyEclipse Persistence Tools
 */
public class TYwClwfSdall extends AbstractTYwClwfSdall implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TYwClwfSdall() {
	}

	/** full constructor */
	public TYwClwfSdall(String xh, String hpzl, String hphm, Date wfsj,
			String wfdz, String wfxw, String cjjg, String clbj, Date clsj,
			Date gxsj, Date drsj, String jdcsyr, String dh) {
		super(xh, hpzl, hphm, wfsj, wfdz, wfxw, cjjg, clbj, clsj, gxsj, drsj,
				jdcsyr, dh);
	}

}
